// Recorded from unit tests by experiments/slim-tests/record-goldens.ts. Outputs live in ../out/agent-receipt.json.
import { type GoldenCases } from "../harness.ts"
import { toAgentReceipt } from "../../../src/agent-receipt.ts"

export const cases: GoldenCases = {
  "toAgentReceipt({\"ok\":true,\"reason\":\"matched\",\"url\":\"https://ironadamant.com\",\"expect\":\"One office job....)": () => toAgentReceipt(({"ok":true,"reason":"matched","url":"https://ironadamant.com","expect":"One office job.","screenshotPath":".auspex/runs/stamp/screenshot.png","title":"Iron Adamant","finalUrl":"https://ironadamant.com/","matched":true,"excerpt":"One office job.","sessionId":"sess","networkIdle":true} as never)),
  "toAgentReceipt({\"ok\":true,\"reason\":\"mismatch\",\"url\":\"https://ironadamant.com\",\"expect\":\"One office job...)": () => toAgentReceipt(({"ok":true,"reason":"mismatch","url":"https://ironadamant.com","expect":"One office job.","screenshotPath":".auspex/runs/stamp/screenshot.png","title":"Iron Adamant","finalUrl":"https://ironadamant.com/","matched":false,"excerpt":"One office job.","sessionId":"sess","networkIdle":true} as never)),
  "toAgentReceipt({\"ok\":false,\"reason\":\"loggedOut\",\"url\":\"https://ironadamant.com\",\"expect\":\"One office j...)": () => toAgentReceipt(({"ok":false,"reason":"loggedOut","url":"https://ironadamant.com","expect":"One office job.","screenshotPath":".auspex/runs/stamp/screenshot.png","title":"Iron Adamant","finalUrl":"https://ironadamant.com/","matched":false,"excerpt":"One office job.","sessionId":"sess","networkIdle":true} as never), ({"verify":{"ok":false,"errors":[],"claimOk":false,"claimErrors":[],"runDir":".auspex/runs/stamp","skipped":true,"skipReason":"loggedOut"}} as never)),
  "toAgentReceipt({\"ok\":true,\"reason\":\"matched\",\"url\":\"https://ironadamant.com\",\"expect\":\"One office job....) #2": () => toAgentReceipt(({"ok":true,"reason":"matched","url":"https://ironadamant.com","expect":"One office job.","screenshotPath":".auspex/runs/stamp/screenshot.png","title":"Iron Adamant","finalUrl":"https://ironadamant.com/","matched":true,"excerpt":"One office job.","sessionId":"sess","networkIdle":true} as never), ({"verify":{"ok":true,"errors":[],"claimOk":false,"claimErrors":["expect missing"],"runDir":".auspex/runs/stamp"}} as never)),
  "toAgentReceipt({\"ok\":true,\"reason\":\"matched\",\"url\":\"https://ironadamant.com\",\"expect\":\"One office job....) #3": () => toAgentReceipt(({"ok":true,"reason":"matched","url":"https://ironadamant.com","expect":"One office job.","screenshotPath":".auspex/runs/stamp/screenshot.png","title":"Iron Adamant","finalUrl":"https://ironadamant.com/","matched":true,"excerpt":"One office job.","sessionId":"sess","networkIdle":true} as never), ({"verify":{"ok":true,"errors":[],"claimOk":false,"claimErrors":["fetched page text does not contain expect"],"runDir":".auspex/runs/stamp"}} as never)),
  "toAgentReceipt({\"ok\":true,\"reason\":\"matched\",\"url\":\"https://ironadamant.com\",\"expect\":\"One office job....) #4": () => toAgentReceipt(({"ok":true,"reason":"matched","url":"https://ironadamant.com","expect":"One office job.","screenshotPath":".auspex/runs/stamp/screenshot.png","title":"Iron Adamant","finalUrl":"https://ironadamant.com/","matched":true,"excerpt":"One office job.","sessionId":"sess","networkIdle":true} as never), ({"verify":{"ok":true,"errors":[],"claimOk":false,"claimErrors":["fetched page text does not contain expect","ocr of screenshot does not contain expect"],"runDir":".auspex/runs/stamp"}} as never)),
  "toAgentReceipt({\"ok\":true,\"reason\":\"matched\",\"url\":\"https://ironadamant.com\",\"expect\":\"One office job....) #5": () => toAgentReceipt(({"ok":true,"reason":"matched","url":"https://ironadamant.com","expect":"One office job.","screenshotPath":".auspex/runs/stamp/screenshot.png","title":"Iron Adamant","finalUrl":"https://ironadamant.com/","matched":true,"excerpt":"One office job.","sessionId":"sess","networkIdle":true} as never), ({"verify":{"ok":true,"errors":[],"claimOk":false,"claimErrors":["fetched page text does not contain expect","ocr unavailable (tesseract not installed)"],"runDir":".auspex/runs/stamp"}} as never)),
  "toAgentReceipt({\"ok\":true,\"reason\":\"matched\",\"url\":\"https://ironadamant.com\",\"expect\":\"One office job....) #6": () => toAgentReceipt(({"ok":true,"reason":"matched","url":"https://ironadamant.com","expect":"One office job.","screenshotPath":".auspex/runs/stamp/screenshot.png","title":"Iron Adamant","finalUrl":"https://ironadamant.com/","matched":true,"excerpt":"One office job.","sessionId":"sess","networkIdle":true} as never), ({"verify":{"ok":true,"errors":[],"claimOk":false,"claimErrors":["anonymous claim skipped"],"anonymousClaimSkipped":true,"runDir":".auspex/runs/stamp"}} as never)),
  "toAgentReceipt({\"ok\":true,\"reason\":\"matched\",\"url\":\"https://ironadamant.com\",\"expect\":\"One office job....) #7": () => toAgentReceipt(({"ok":true,"reason":"matched","url":"https://ironadamant.com","expect":"One office job.","screenshotPath":".auspex/runs/stamp/screenshot.png","title":"Iron Adamant","finalUrl":"https://ironadamant.com/","matched":true,"excerpt":"One office job.","sessionId":"sess","networkIdle":true} as never), ({"verify":{"ok":false,"errors":["sandbox verify timed out after 90000ms"],"claimOk":false,"claimErrors":[],"anonymousClaimSkipped":true,"claimOkProfile":false,"claimErrorsProfile":["sandbox verify timed out after 90000ms"],"runDir":".auspex/runs/stamp"}} as never)),
  "toAgentReceipt({\"ok\":true,\"reason\":\"matched\",\"url\":\"https://ironadamant.com\",\"expect\":\"One office job....) #8": () => toAgentReceipt(({"ok":true,"reason":"matched","url":"https://ironadamant.com","expect":"One office job.","screenshotPath":".auspex/runs/stamp/screenshot.png","title":"Iron Adamant","finalUrl":"https://ironadamant.com/","matched":true,"excerpt":"One office job.","sessionId":"sess","networkIdle":true} as never), ({"verify":{"ok":true,"errors":[],"claimOk":false,"claimErrors":["anonymous claim skipped"],"anonymousClaimSkipped":true,"claimOkProfile":true,"runDir":".auspex/runs/stamp"}} as never)),
  "toAgentReceipt({\"ok\":true,\"reason\":\"matched\",\"url\":\"https://ironadamant.com\",\"expect\":\"One office job....) #9": () => toAgentReceipt(({"ok":true,"reason":"matched","url":"https://ironadamant.com","expect":"One office job.","screenshotPath":".auspex/runs/stamp/screenshot.png","title":"Iron Adamant","finalUrl":"https://ironadamant.com/","matched":true,"excerpt":"One office job.","sessionId":"sess","networkIdle":true} as never), ({"verify":{"ok":true,"errors":[],"claimOk":false,"claimErrors":["anonymous claim skipped"],"anonymousClaimSkipped":true,"claimOkProfile":false,"claimErrorsProfile":["expect missing"],"runDir":".auspex/runs/stamp"}} as never)),
  "toAgentReceipt({\"ok\":true,\"reason\":\"matched\",\"url\":\"https://ironadamant.com\",\"expect\":\"One office job....) #10": () => toAgentReceipt(({"ok":true,"reason":"matched","url":"https://ironadamant.com","expect":"One office job.","screenshotPath":".auspex/runs/stamp/screenshot.png","title":"Iron Adamant","finalUrl":"https://ironadamant.com/","matched":true,"excerpt":"One office job.","sessionId":"sess","networkIdle":true} as never), ({"verify":{"ok":true,"errors":[],"claimOk":true,"claimErrors":[],"runDir":".auspex/runs/stamp"}} as never)),
  "toAgentReceipt({\"ok\":false,\"reason\":\"mismatch\",\"url\":\"https://ironadamant.com\",\"expect\":\"One office jo...)": () => toAgentReceipt(({"ok":false,"reason":"mismatch","url":"https://ironadamant.com","expect":"One office job.","screenshotPath":".auspex/runs/stamp/screenshot.png","title":"Iron Adamant","finalUrl":"https://ironadamant.com/","matched":false,"excerpt":"One office job.","sessionId":"sess","networkIdle":true,"protocolOk":true} as never)),
  "toAgentReceipt({\"ok\":true,\"protocolOk\":true,\"reason\":\"hostChanged\",\"hostChanged\":true,\"profileHostMatc...)": () => toAgentReceipt(({"ok":true,"protocolOk":true,"reason":"hostChanged","hostChanged":true,"profileHostMatch":false,"suggestedProfile":"app-socialaize-com","suggestedUrl":"https://app.socialaize.com","url":"https://myapp.example","expect":"Workspace ready","screenshotPath":".auspex/runs/x/screenshot.png","title":"App","finalUrl":"https://app.socialaize.com/","matched":false,"excerpt":"switched","sessionId":"sess","networkIdle":true,"next":"Live host changed: remint","nextCall":{"tool":"auspex_login","profile":"app-socialaize-com","url":"https://app.socialaize.com"}} as never), ({"verify":{"ok":true,"errors":[],"claimOk":false,"claimErrors":[],"claimOkProfile":true,"runDir":".auspex/runs/x","skipped":true,"skipReason":"hostChanged"}} as never)),
  "toAgentReceipt({\"ok\":false,\"reason\":\"needsHuman\",\"url\":\"https://app.example/dashboard\",\"expect\":\"Dashb...)": () => toAgentReceipt(({"ok":false,"reason":"needsHuman","url":"https://app.example/dashboard","expect":"Dashboard","screenshotPath":".auspex/runs/stamp/screenshot.png","title":"Sign in","finalUrl":"https://login.microsoftonline.com/","matched":false,"excerpt":"Enter password","sessionId":"sess-should-not-enter-next-call","networkIdle":true,"needsHuman":true,"next":"Stop. Microsoft or Google password/OTP wall detected. Call auspex_login --profile app-example and show handoff.url (phone.html, the only login door, on a phone or a computer). handoff.mobileUrl is that same page, with a real text field so the phone keyboard can open. Never type in Solari's remote Chromium / noVNC card on a phone: that stream is a picture of Chrome, so the phone software keyboard will not open. Auspex phone.html is a seed/handoff door for off-site typing (IME + Save paste), not a same-session VNC takeover of the agent's live check. Never fill password via agent tools. After human completes sign-in and Save: await-login --profile app-example --save-editor then finalize-login --profile app-example --url <url> --expect <string>. Do not retry check on cookies alone. Never --record. This is a re-gate. Stop the loop. One human door. Do not auto-fill a secret or claim a challenge is solved. This seed is not overnight-safe. Guide: AGENTS.md, Long unattended loops. password hunter2secret token slr_live_abcdefghij","nextCall":{"tool":"auspex_login","profile":"app-example"}} as never)),
  "toAgentReceipt({\"ok\":true,\"reason\":\"matched\",\"url\":\"https://app.socialaize.com\",\"expect\":\"Dashboard\",\"...)": () => toAgentReceipt(({"ok":true,"reason":"matched","url":"https://app.socialaize.com","expect":"Dashboard","screenshotPath":".auspex/runs/stamp/screenshot.png","title":"Socialaize","finalUrl":"https://app.socialaize.com/","matched":true,"excerpt":"Dashboard","sessionId":"sess","networkIdle":true,"profileHostMatch":false,"suggestedProfile":"app-socialaize-com","next":"Profile host mismatch: remint","nextCall":{"tool":"auspex_login","profile":"app-socialaize-com","url":"https://app.socialaize.com"}} as never)),
}
