// Recorded from unit tests by experiments/slim-tests/record-goldens.ts. Outputs live in ../out/await-steer.json.
import { type GoldenCases } from "../harness.ts"
import { steerAwaitLogin } from "../../../src/await-steer.ts"

export const cases: GoldenCases = {
  "steerAwaitLogin({\"patch\":{\"next\":\"remint the live host\",\"nextCall\":{\"tool\":\"auspex_login\",\"profile\":\"ap...)": () => steerAwaitLogin(({"patch":{"next":"remint the live host","nextCall":{"tool":"auspex_login","profile":"app-socialaize-com"}},"steered":{"status":"host-changed","name":"app-example","next":"still waiting","cookies":3,"origins":1,"cookieHosts":["app.example"],"sessionStorage":0},"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"streamExpired":true,"editorHung":true,"profileBusy":true,"siteHost":"app.example","guideUrl":"https://app.example","guideExpect":"Workspace ready"} as never)),
  "steerAwaitLogin({\"steered\":{\"status\":\"timeout\",\"name\":\"app-example\",\"next\":\"still waiting\",\"cookies\":3,...)": () => steerAwaitLogin(({"steered":{"status":"timeout","name":"app-example","next":"still waiting","cookies":3,"origins":1,"cookieHosts":["cdn.tracker.test"],"sessionStorage":0},"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"streamExpired":true,"editorHung":true,"profileBusy":true,"siteHost":"app.example","guideUrl":"https://app.example/app","guideExpect":"Workspace ready"} as never)),
  "steerAwaitLogin({\"steered\":{\"status\":\"waiting\",\"name\":\"app-example\",\"next\":\"still waiting\",\"cookies\":3,...)": () => steerAwaitLogin(({"steered":{"status":"waiting","name":"app-example","next":"still waiting","cookies":3,"origins":1,"cookieHosts":["cdn.tracker.test"],"sessionStorage":0},"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"streamExpired":false,"editorHung":false,"profileBusy":false,"siteHost":"app.example","guideUrl":"https://app.example/app","guideExpect":"Workspace ready"} as never)),
  "steerAwaitLogin({\"steered\":{\"status\":\"timeout\",\"name\":\"app-example\",\"next\":\"still waiting\",\"cookies\":3,...) #2": () => steerAwaitLogin(({"steered":{"status":"timeout","name":"app-example","next":"still waiting","cookies":3,"origins":1,"cookieHosts":["app.example"],"sessionStorage":0},"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"streamExpired":true,"editorHung":true,"profileBusy":true,"siteHost":"app.example","guideUrl":"https://app.example/app","guideExpect":"Workspace ready"} as never)),
  "steerAwaitLogin({\"steered\":{\"status\":\"waiting\",\"name\":\"app-example\",\"next\":\"still waiting\",\"cookies\":0,...)": () => steerAwaitLogin(({"steered":{"status":"waiting","name":"app-example","next":"still waiting","cookies":0,"origins":0,"cookieHosts":[],"sessionStorage":0},"streamExpired":true,"editorHung":true,"profileBusy":true} as never)),
  "steerAwaitLogin({\"steered\":{\"status\":\"waiting\",\"name\":\"app-example\",\"next\":\"still waiting\",\"cookies\":0,...) #2": () => steerAwaitLogin(({"steered":{"status":"waiting","name":"app-example","next":"still waiting","cookies":0,"origins":0,"cookieHosts":[],"sessionStorage":0},"streamExpired":false,"editorHung":true,"profileBusy":true} as never)),
  "steerAwaitLogin({\"steered\":{\"status\":\"waiting\",\"name\":\"app-example\",\"next\":\"still waiting\",\"cookies\":0,...) #3": () => steerAwaitLogin(({"steered":{"status":"waiting","name":"app-example","next":"still waiting","cookies":0,"origins":0,"cookieHosts":[],"sessionStorage":0},"streamExpired":false,"editorHung":false,"profileBusy":true} as never)),
  "steerAwaitLogin({\"steered\":{\"status\":\"idp-only-save\",\"name\":\"app-example\",\"next\":\"picture is not a save...)": () => steerAwaitLogin(({"steered":{"status":"idp-only-save","name":"app-example","next":"picture is not a saved login","cookies":3,"origins":1,"cookieHosts":["login.microsoftonline.com"],"sessionStorage":0,"liveHost":"app.example"},"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"streamExpired":true,"editorHung":false,"profileBusy":false,"siteHost":"app.example"} as never)),
  "steerAwaitLogin({\"steered\":{\"status\":\"idp-only-save\",\"name\":\"app-example\",\"next\":\"finish sign-in\",\"cook...)": () => steerAwaitLogin(({"steered":{"status":"idp-only-save","name":"app-example","next":"finish sign-in","cookies":3,"origins":1,"cookieHosts":["login.microsoftonline.com"],"sessionStorage":0,"nextCall":{"tool":"auspex_login","profile":"app-example"},"liveHost":"login.microsoftonline.com"},"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"streamExpired":true,"editorHung":false,"profileBusy":false,"siteHost":"app.example"} as never)),
  "steerAwaitLogin({\"steered\":{\"status\":\"stream-expired\",\"name\":\"app-example\",\"next\":\"still waiting\",\"cook...)": () => steerAwaitLogin(({"steered":{"status":"stream-expired","name":"app-example","next":"still waiting","cookies":2,"origins":1,"cookieHosts":["login.microsoftonline.com"],"sessionStorage":0},"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"streamExpired":true,"editorHung":false,"profileBusy":false,"siteHost":"app.example"} as never)),
  "steerAwaitLogin({\"steered\":{\"status\":\"completed\",\"name\":\"app-example\",\"next\":\"saved\",\"cookies\":3,\"origi...)": () => steerAwaitLogin(({"steered":{"status":"completed","name":"app-example","next":"saved","cookies":3,"origins":1,"cookieHosts":["app.example"],"sessionStorage":0,"nextCall":{"tool":"auspex_finalize_login","profile":"app-example"}},"editorSave":{"ok":false,"status":401,"error":"unauthorized"},"streamExpired":false,"editorHung":false,"profileBusy":false,"siteHost":"app.example"} as never)),
  "steerAwaitLogin({\"steered\":{\"status\":\"timeout\",\"name\":\"app-example\",\"next\":\"No non-empty Save yet for a...)": () => steerAwaitLogin(({"steered":{"status":"timeout","name":"app-example","next":"No non-empty Save yet for app-example.","cookies":0,"origins":0,"cookieHosts":[],"sessionStorage":0},"editorSave":{"ok":false,"status":502,"error":"Failed to export storageState"},"streamExpired":false,"editorHung":false,"profileBusy":false} as never)),
  "steerAwaitLogin({\"steered\":{\"status\":\"timeout\",\"name\":\"app-example\",\"next\":\"still waiting\",\"cookies\":0,...)": () => steerAwaitLogin(({"steered":{"status":"timeout","name":"app-example","next":"still waiting","cookies":0,"origins":0,"cookieHosts":[],"sessionStorage":0},"editorSave":{"ok":false,"status":502,"error":"Failed to export storageState"},"streamExpired":true,"editorHung":false,"profileBusy":false} as never)),
  "steerAwaitLogin({\"steered\":{\"status\":\"timeout\",\"name\":\"app-example\",\"next\":\"still waiting\",\"cookies\":0,...) #2": () => steerAwaitLogin(({"steered":{"status":"timeout","name":"app-example","next":"still waiting","cookies":0,"origins":0,"cookieHosts":[],"sessionStorage":0},"editorSave":{"ok":false,"status":503,"error":"Failed to export storageState"},"streamExpired":true,"editorHung":false,"profileBusy":false} as never)),
  "steerAwaitLogin({\"steered\":{\"status\":\"timeout\",\"name\":\"app-example\",\"next\":\"still waiting\",\"cookies\":0,...) #3": () => steerAwaitLogin(({"steered":{"status":"timeout","name":"app-example","next":"still waiting","cookies":0,"origins":0,"cookieHosts":[],"sessionStorage":0},"editorSave":{"ok":false,"status":504,"error":"Failed to export storageState"},"streamExpired":true,"editorHung":false,"profileBusy":false} as never)),
  "steerAwaitLogin({\"steered\":{\"status\":\"completed\",\"name\":\"app-example\",\"next\":\"saved\",\"cookies\":4,\"origi...)": () => steerAwaitLogin(({"steered":{"status":"completed","name":"app-example","next":"saved","cookies":4,"origins":1,"cookieHosts":["app.example"],"sessionStorage":0,"nextCall":{"tool":"auspex_check","profile":"app-example","verifyWithProfile":true}},"editorSave":{"ok":false,"status":409,"error":"not in a savable state"},"streamExpired":true,"editorHung":false,"profileBusy":false,"notSavableExhausted":true,"siteHost":"app.example"} as never)),
  "steerAwaitLogin({\"steered\":{\"status\":\"completed\",\"name\":\"app-example\",\"next\":\"saved\",\"cookies\":0,\"origi...)": () => steerAwaitLogin(({"steered":{"status":"completed","name":"app-example","next":"saved","cookies":0,"origins":0,"cookieHosts":["app.example"],"sessionStorage":0},"editorSave":{"ok":false,"status":409,"error":"not in a savable state","tokenStatus":409},"streamExpired":true,"editorHung":false,"profileBusy":false,"notSavableExhausted":true,"editorRefusedSave":true,"siteHost":"app.example"} as never)),
  "steerAwaitLogin({\"steered\":{\"status\":\"empty-save\",\"name\":\"app-example\",\"next\":\"Save bumped the profile ...)": () => steerAwaitLogin(({"steered":{"status":"empty-save","name":"app-example","next":"Save bumped the profile to v3 but stored no cookies or origins. Do not reuse --profile app-example until a non-empty Save.","cookies":0,"origins":0,"cookieHosts":[],"sessionStorage":0},"editorSave":{"ok":false,"status":413,"error":"Payload Too Large"},"editorFold":{"ok":false,"reason":"no-cdp"},"streamExpired":false,"editorHung":false,"profileBusy":false} as never)),
  "steerAwaitLogin({\"steered\":{\"status\":\"empty-save\",\"name\":\"app-example\",\"next\":\"Save bumped the profile ...) #2": () => steerAwaitLogin(({"steered":{"status":"empty-save","name":"app-example","next":"Save bumped the profile to v4 but stored no cookies or origins. Do not reuse --profile app-example until a non-empty Save.","cookies":0,"origins":0,"cookieHosts":[],"sessionStorage":0},"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"streamExpired":false,"editorHung":false,"profileBusy":false,"siteHost":"app.example"} as never)),
  "steerAwaitLogin({\"steered\":{\"status\":\"timeout\",\"name\":\"app-example\",\"next\":\"No non-empty Save yet for a...) #2": () => steerAwaitLogin(({"steered":{"status":"timeout","name":"app-example","next":"No non-empty Save yet for app-example. Keep the handoff open, Save, then retry auspex_await_login.","cookies":0,"origins":0,"cookieHosts":[],"sessionStorage":0},"editorSave":{"ok":false,"status":502,"error":"Failed to export storageState"},"streamExpired":false,"editorHung":false,"profileBusy":false} as never)),
}
