// Recorded from unit tests by experiments/slim-tests/record-goldens.ts. Outputs live in ../out/check-reason.json.
import { type GoldenCases } from "../harness.ts"
import { agentReceiptOk, deriveCheckReason, expectOnUnpersistableLanding, overlayVerifyReason } from "../../../src/check-reason.ts"

export const cases: GoldenCases = {
  "deriveCheckReason({\"matched\":true,\"networkIdle\":true,\"finalUrl\":\"https://ironadamant.com/\",\"excerpt\":\"One...)": () => deriveCheckReason(({"matched":true,"networkIdle":true,"finalUrl":"https://ironadamant.com/","excerpt":"One office job.","screenshotOk":true} as never)),
  "deriveCheckReason({\"matched\":false,\"networkIdle\":true,\"finalUrl\":\"https://ironadamant.com/\",\"excerpt\":\"he...)": () => deriveCheckReason(({"matched":false,"networkIdle":true,"finalUrl":"https://ironadamant.com/","excerpt":"hello","screenshotOk":true} as never)),
  "deriveCheckReason({\"matched\":false,\"networkIdle\":false,\"finalUrl\":\"\",\"excerpt\":\"\",\"screenshotOk\":false})": () => deriveCheckReason(({"matched":false,"networkIdle":false,"finalUrl":"","excerpt":"","screenshotOk":false} as never)),
  "deriveCheckReason({\"special\":\"loggedOut\",\"matched\":false,\"networkIdle\":true,\"finalUrl\":\"https://consisten...)": () => deriveCheckReason(({"special":"loggedOut","matched":false,"networkIdle":true,"finalUrl":"https://consistencyhub.io/landing","excerpt":"Sign in","screenshotOk":true} as never)),
  "deriveCheckReason({\"special\":\"needsHuman\",\"needsHuman\":true,\"matched\":false,\"networkIdle\":true,\"finalUrl\"...)": () => deriveCheckReason(({"special":"needsHuman","needsHuman":true,"matched":false,"networkIdle":true,"finalUrl":"https://login.microsoftonline.com/","excerpt":"password","screenshotOk":true} as never)),
  "overlayVerifyReason(\"matched\", {\"ok\":true,\"claimOk\":true,\"errors\":[],\"claimErrors\":[]})": () => overlayVerifyReason("matched", ({"ok":true,"claimOk":true,"errors":[],"claimErrors":[]} as never)),
  "overlayVerifyReason(\"matched\", {\"ok\":true,\"claimOk\":false,\"errors\":[],\"claimErrors\":[\"expect not found\"]})": () => overlayVerifyReason("matched", ({"ok":true,"claimOk":false,"errors":[],"claimErrors":["expect not found"]} as never)),
  "overlayVerifyReason(\"loggedOut\", {\"ok\":false,\"claimOk\":false,\"errors\":[\"fetch failed\"]})": () => overlayVerifyReason("loggedOut", ({"ok":false,"claimOk":false,"errors":["fetch failed"]} as never)),
  "overlayVerifyReason(\"expectMatchedPublicLanding\", {\"ok\":false,\"claimOk\":false,\"errors\":[\"expect not found\"]})": () => overlayVerifyReason("expectMatchedPublicLanding", ({"ok":false,"claimOk":false,"errors":["expect not found"]} as never)),
  "overlayVerifyReason(\"matched\", {\"ok\":false,\"claimOk\":false,\"errors\":[\"network timeout\"]})": () => overlayVerifyReason("matched", ({"ok":false,"claimOk":false,"errors":["network timeout"]} as never)),
  "agentReceiptOk({\"protocolOk\":true,\"reason\":\"matched\"})": () => agentReceiptOk(({"protocolOk":true,"reason":"matched"} as never)),
  "agentReceiptOk({\"protocolOk\":true,\"reason\":\"mismatch\"})": () => agentReceiptOk(({"protocolOk":true,"reason":"mismatch"} as never)),
  "overlayVerifyReason(\"matched\", {\"ok\":true,\"claimOk\":false,\"anonymousClaimSkipped\":true,\"claimErrors\":[\"anon...)": () => overlayVerifyReason("matched", ({"ok":true,"claimOk":false,"anonymousClaimSkipped":true,"claimErrors":["anonymous claim skipped"]} as never)),
  "overlayVerifyReason(\"matched\", {\"ok\":false,\"claimOk\":false,\"anonymousClaimSkipped\":true,\"errors\":[\"sandbox ...)": () => overlayVerifyReason("matched", ({"ok":false,"claimOk":false,"anonymousClaimSkipped":true,"errors":["sandbox verify timed out after 90000ms"]} as never)),
  "agentReceiptOk({\"protocolOk\":true,\"reason\":\"matched\",\"verify\":{\"ok\":true,\"claimOk\":false,\"anonymousCla...)": () => agentReceiptOk(({"protocolOk":true,"reason":"matched","verify":{"ok":true,"claimOk":false,"anonymousClaimSkipped":true}} as never)),
  "expectOnUnpersistableLanding({\"saveProfile\":true,\"textMatched\":true,\"finalUrl\":\"https://app.example/\",\"needsHuman\":f...)": () => expectOnUnpersistableLanding(({"saveProfile":true,"textMatched":true,"finalUrl":"https://app.example/","needsHuman":false} as never)),
  "expectOnUnpersistableLanding({\"saveProfile\":true,\"textMatched\":true,\"finalUrl\":\"https://app.example/login\",\"needsHum...)": () => expectOnUnpersistableLanding(({"saveProfile":true,"textMatched":true,"finalUrl":"https://app.example/login","needsHuman":false} as never)),
  "expectOnUnpersistableLanding({\"saveProfile\":true,\"textMatched\":true,\"finalUrl\":\"https://app.example/dashboard\",\"need...)": () => expectOnUnpersistableLanding(({"saveProfile":true,"textMatched":true,"finalUrl":"https://app.example/dashboard","needsHuman":false} as never)),
  "expectOnUnpersistableLanding({\"saveProfile\":false,\"textMatched\":true,\"finalUrl\":\"https://app.example/\",\"needsHuman\":...)": () => expectOnUnpersistableLanding(({"saveProfile":false,"textMatched":true,"finalUrl":"https://app.example/","needsHuman":false} as never)),
  "deriveCheckReason({\"special\":\"expectMatchedPublicLanding\",\"matched\":false,\"networkIdle\":true,\"finalUrl\":\"...)": () => deriveCheckReason(({"special":"expectMatchedPublicLanding","matched":false,"networkIdle":true,"finalUrl":"https://app.example/","excerpt":"10+ Platforms , One Dashboard. Welcome to your workspace","screenshotOk":true} as never)),
  "agentReceiptOk({\"protocolOk\":false,\"reason\":\"expectMatchedPublicLanding\"})": () => agentReceiptOk(({"protocolOk":false,"reason":"expectMatchedPublicLanding"} as never)),
  "deriveCheckReason({\"special\":\"hostChanged\",\"needsHuman\":true,\"matched\":true,\"networkIdle\":true,\"finalUrl\"...)": () => deriveCheckReason(({"special":"hostChanged","needsHuman":true,"matched":true,"networkIdle":true,"finalUrl":"https://app.socialaize.com/","excerpt":"x","screenshotOk":true} as never)),
}
