// Recorded from unit tests by experiments/slim-tests/record-goldens.ts. Outputs live in ../out/cli.json.
import { type GoldenCases } from "../harness.ts"
import { parseArgv } from "../../../src/cli.ts"

export const cases: GoldenCases = {
  "parseArgv(([\"check\",\"https://consistencyhub.io/login\",\"--expect\",\"Dashboard\",\"--profile\",\"consist...)": () => parseArgv((["check","https://consistencyhub.io/login","--expect","Dashboard","--profile","consistencyhub","--sso"] as never)),
  "parseArgv(([\"check\",\"https://ironadamant.com\",\"--expect\",\"Build it.\",\"--stealth=true\"]))": () => parseArgv((["check","https://ironadamant.com","--expect","Build it.","--stealth=true"] as never)),
  "parseArgv(([\"login\",\"--profile\",\"auspex-goal-test\"]))": () => parseArgv((["login","--profile","auspex-goal-test"] as never)),
  "parseArgv(([\"profiles\"]))": () => parseArgv((["profiles"] as never)),
  "parseArgv(([\"login\",\"--profile\",\"auspex-demo\",\"--wait\"]))": () => parseArgv((["login","--profile","auspex-demo","--wait"] as never)),
  "parseArgv(([\"await-login\",\"--profile\",\"auspex-demo\",\"--since-version\",\"10\"]))": () => parseArgv((["await-login","--profile","auspex-demo","--since-version","10"] as never)),
  "parseArgv(([\"await-login\",\"--profile\",\"auspex-demo\",\"--save-editor\"]))": () => parseArgv((["await-login","--profile","auspex-demo","--save-editor"] as never)),
  "parseArgv(([\"check\",\"https://consistencyhub.io\",\"--expect\",\"Document Editor\",\"--sso\",\"--record\"]))": () => parseArgv((["check","https://consistencyhub.io","--expect","Document Editor","--sso","--record"] as never)),
  "parseArgv(([\"check\",\"https://consistencyhub.io\",\"--expect\",\"Document Editor\",\"--profile\",\"consist...)": () => parseArgv((["check","https://consistencyhub.io","--expect","Document Editor","--profile","consistencyhub","--save-profile","--record","--allow-record-profile"] as never)),
  "parseArgv(([\"check\",\"https://ironadamant.com\",\"--expect\",\"Build it.\",\"--profile\",\"demo\",\"--record\"]))": () => parseArgv((["check","https://ironadamant.com","--expect","Build it.","--profile","demo","--record"] as never)),
  "parseArgv(([\"check\",\"https://ironadamant.com\",\"--expect\",\"Build it.\",\"--profile\",\"demo\",\"--record...)": () => parseArgv((["check","https://ironadamant.com","--expect","Build it.","--profile","demo","--record","--allow-record-profile"] as never)),
  "parseArgv(([\"check\",\"--name\",\"consistencyhub\",\"--record\",\"--allow-record-profile\"]))": () => parseArgv((["check","--name","consistencyhub","--record","--allow-record-profile"] as never)),
  "parseArgv(([\"check\",\"https://ironadamant.com\",\"--expect\",\"Build it.\",\"--wait-for\",\"#main\",\"--fill...)": () => parseArgv((["check","https://ironadamant.com","--expect","Build it.","--wait-for","#main","--fill","#q","--value","hello","--click","button.submit","--proxy","us","--captcha"] as never)),
  "parseArgv(([\"check\",\"--name\",\"consistencyhub\",\"--click\",\"button.export\"]))": () => parseArgv((["check","--name","consistencyhub","--click","button.export"] as never)),
  "parseArgv(([\"check\",\"--name\",\"consistencyhub\",\"--click\",\"button.export\",\"--allow-page-actions\"]))": () => parseArgv((["check","--name","consistencyhub","--click","button.export","--allow-page-actions"] as never)),
  "parseArgv(([\"check\",\"https://example.com\",\"--expect\",\"Example Domain\",\"--profile\",\"auspex-demo\",\"...)": () => parseArgv((["check","https://example.com","--expect","Example Domain","--profile","auspex-demo","--save-profile"] as never)),
  "parseArgv(([\"reap\",\"--dry-run\",\"--session\",\"sess-1\"]))": () => parseArgv((["reap","--dry-run","--session","sess-1"] as never)),
  "parseArgv(([\"reap\",\"--account-wide\"]))": () => parseArgv((["reap","--account-wide"] as never)),
  "parseArgv(([\"desktop\",\"--open\",\"mousepad\",\"--expect\",\"mousepad\"]))": () => parseArgv((["desktop","--open","mousepad","--expect","mousepad"] as never)),
  "parseArgv(([\"check\",\"--name\",\"ironadamant\"]))": () => parseArgv((["check","--name","ironadamant"] as never)),
  "parseArgv(([\"check\",\"--name\",\"consistencyhub\"]))": () => parseArgv((["check","--name","consistencyhub"] as never)),
  "parseArgv(([\"check\",\"--name\",\"checkpoint\",\"--no-verify\"]))": () => parseArgv((["check","--name","checkpoint","--no-verify"] as never)),
  "parseArgv(([\"check\",\"https://consistencyhub.io/dashboard\",\"--expect\",\"Document Editor\",\"--record\"]))": () => parseArgv((["check","https://consistencyhub.io/dashboard","--expect","Document Editor","--record"] as never)),
  "parseArgv(([\"profile-status\",\"--name\",\"consistencyhub\"]))": () => parseArgv((["profile-status","--name","consistencyhub"] as never)),
  "parseArgv(([\"profile-status\",\"--profile\",\"app-example\",\"--url\",\"https://app.example\",\"--expect\",\"...)": () => parseArgv((["profile-status","--profile","app-example","--url","https://app.example","--expect","Workspace ready"] as never)),
  "parseArgv(([\"profile-status\",\"--profile\",\"app-example\",\"--expect\",\"\"]))": () => parseArgv((["profile-status","--profile","app-example","--expect",""] as never)),
  "parseArgv(([\"reap\",\"--dry-run\",\"--pack-receipts\"]))": () => parseArgv((["reap","--dry-run","--pack-receipts"] as never)),
  "parseArgv(([\"desktop\"]))": () => parseArgv((["desktop"] as never)),
  "parseArgv(([\"desktop\",\"extra\"]))": () => parseArgv((["desktop","extra"] as never)),
  "parseArgv(([\"check\",\"https://onedrive.live.com/\",\"--expect\",\"My files\",\"--profile\",\"consistencyhu...)": () => parseArgv((["check","https://onedrive.live.com/","--expect","My files","--profile","consistencyhub"] as never)),
  "parseArgv(([\"check\",\"https://consistencyhub.io\",\"--expect\",\"Document Editor\",\"--profile\",\"consist...) #2": () => parseArgv((["check","https://consistencyhub.io","--expect","Document Editor","--profile","consistencyhub"] as never)),
  "parseArgv(([\"check\",\"https://ironadamant.com\",\"--expect\",\"One office job.\",\"--profile\",\"demo\"]))": () => parseArgv((["check","https://ironadamant.com","--expect","One office job.","--profile","demo"] as never)),
  "parseArgv(([\"check\",\"https://app.example.com\",\"--expect\",\"Dashboard\",\"--profile\",\"acme\"]))": () => parseArgv((["check","https://app.example.com","--expect","Dashboard","--profile","acme"] as never)),
  "parseArgv(([\"check\",\"https://app.example.com\",\"--expect\",\"Dashboard\"]))": () => parseArgv((["check","https://app.example.com","--expect","Dashboard"] as never)),
  "parseArgv(([\"check\",\"--name\",\"consistencyhub\",\"--verify-with-profile\"]))": () => parseArgv((["check","--name","consistencyhub","--verify-with-profile"] as never)),
  "parseArgv(([\"check\",\"--name\",\"consistencyhub\",\"--verify\"]))": () => parseArgv((["check","--name","consistencyhub","--verify"] as never)),
  "parseArgv(([\"check\",\"--name\",\"consistencyhub\",\"--no-verify\"]))": () => parseArgv((["check","--name","consistencyhub","--no-verify"] as never)),
  "parseArgv(([\"connect\",\"https://app.example\"]))": () => parseArgv((["connect","https://app.example"] as never)),
  "parseArgv(([\"finalize-login\",\"--profile\",\"myapp\"]))": () => parseArgv((["finalize-login","--profile","myapp"] as never)),
  "parseArgv(([\"finalize-login\",\"--profile\",\"myapp\",\"--url\",\"https://app.example.com\",\"--expect\",\"Da...)": () => parseArgv((["finalize-login","--profile","myapp","--url","https://app.example.com","--expect","Dashboard"] as never)),
  "parseArgv(([\"job\",\"--url\",\"https://app.example\",\"--expect\",\"Workspace ready\",\"--verify-with-profi...)": () => parseArgv((["job","--url","https://app.example","--expect","Workspace ready","--verify-with-profile","--wake-webhook","https://hooks.example/wake"] as never)),
  "parseArgv(([\"job-status\",\"--job-id\",\"job-abc-12345678\",\"--wait-ms\",\"500\"]))": () => parseArgv((["job-status","--job-id","job-abc-12345678","--wait-ms","500"] as never)),
  "parseArgv(([\"trace\",\"--profile\",\"consistencyhub\",\"--limit\",\"20\"]))": () => parseArgv((["trace","--profile","consistencyhub","--limit","20"] as never)),
  "parseArgv(([\"trace\",\"--all\"]))": () => parseArgv((["trace","--all"] as never)),
  "parseArgv(([\"check\",\"https://example.com\",\"--expect\",\"Example Domain\",\"--fill\",\"#q\",\"--value\",\"hi...)": () => parseArgv((["check","https://example.com","--expect","Example Domain","--fill","#q","--value","hi","--click","button.go"] as never)),
  "parseArgv(([\"check\",\"https://example.com\",\"--expect\",\"Example Domain\",\"--fill\",\"#a\",\"--value\",\"on...)": () => parseArgv((["check","https://example.com","--expect","Example Domain","--fill","#a","--value","one","--fill","#b"] as never)),
  "parseArgv(([\"check\",\"https://example.com\",\"--expect\",\"Example Domain\",\"--click\",\"button.open\",\"--...)": () => parseArgv((["check","https://example.com","--expect","Example Domain","--click","button.open","--click","button.save"] as never)),
  "parseArgv(([\"await-login\",\"--profile\",\"consistencyhub\",\"--url\",\"https://app.socialaize.com\",\"--sa...)": () => parseArgv((["await-login","--profile","consistencyhub","--url","https://app.socialaize.com","--save-editor"] as never)),
  "parseArgv(([\"await-login\",\"--profile\",\"consistencyhub\",\"--url\",\"file:///tmp\"]))": () => parseArgv((["await-login","--profile","consistencyhub","--url","file:///tmp"] as never)),
  "parseArgv(([\"login\",\"--url\",\"https://app.example.com\"]))": () => parseArgv((["login","--url","https://app.example.com"] as never)),
  "parseArgv(([\"login\",\"--url\",\"https://app.example\"]))": () => parseArgv((["login","--url","https://app.example"] as never)),
  "parseArgv(([\"login\",\"--profile\",\"consistencyhub\",\"--url\",\"https://app.example.com\"]))": () => parseArgv((["login","--profile","consistencyhub","--url","https://app.example.com"] as never)),
  "parseArgv(([\"login\"]))": () => parseArgv((["login"] as never)),
  "parseArgv(([\"check\",\"https://ironadamant.com\",\"--expect\",\"Build it.\",\"--verify\"]))": () => parseArgv((["check","https://ironadamant.com","--expect","Build it.","--verify"] as never)),
  "parseArgv(([\"verify\"]))": () => parseArgv((["verify"] as never)),
  "parseArgv(([\"verify\",\".auspex/runs/stamp\"]))": () => parseArgv((["verify",".auspex/runs/stamp"] as never)),
  "parseArgv(([\"solari-health\"]))": () => parseArgv((["solari-health"] as never)),
  "parseArgv(([\"solari-health\",\"--profile\",\"app-example\"]))": () => parseArgv((["solari-health","--profile","app-example"] as never)),
  "parseArgv(([\"solari-health\",\"--help\"]))": () => parseArgv((["solari-health","--help"] as never)),
}
