// Recorded from unit tests by experiments/slim-tests/record-goldens.ts. Outputs live in ../out/cookie-save.json.
import { type GoldenCases } from "../harness.ts"
import { classifySeedReadiness, cookieSaveGuide, isSafeAuthKeyName, localStorageAuthKeyNames, parseAuthKeyNames } from "../../../src/cookie-save.ts"

export const cases: GoldenCases = {
  "classifySeedReadiness({\"profile\":\"app-example-com\",\"url\":\"https://app.example.com/home\",\"cookies\":4,\"origins\"...)": () => classifySeedReadiness(({"profile":"app-example-com","url":"https://app.example.com/home","cookies":4,"origins":1,"sessionStorage":0,"cookieHosts":["example.com","login.microsoftonline.com"]} as never)),
  "classifySeedReadiness({\"profile\":\"consistencyhub\",\"url\":\"https://consistencyhub.io\",\"cookies\":6,\"origins\":2,\"...)": () => classifySeedReadiness(({"profile":"consistencyhub","url":"https://consistencyhub.io","cookies":6,"origins":2,"sessionStorage":0,"cookieHosts":["login.microsoftonline.com","login.live.com"],"localStorageAuthKeyNames":["accessToken"]} as never)),
  "classifySeedReadiness({\"profile\":\"consistencyhub\",\"url\":\"https://consistencyhub.io\",\"cookies\":6,\"origins\":2,\"...) #2": () => classifySeedReadiness(({"profile":"consistencyhub","url":"https://consistencyhub.io","cookies":6,"origins":2,"sessionStorage":0,"cookieHosts":["login.microsoftonline.com","www.google.com"],"liveHost":"consistencyhub.io"} as never)),
  "classifySeedReadiness({\"profile\":\"ironadamant\",\"url\":\"https://ironadamant.com\",\"cookies\":4,\"origins\":1,\"sessi...)": () => classifySeedReadiness(({"profile":"ironadamant","url":"https://ironadamant.com","cookies":4,"origins":1,"sessionStorage":0,"cookieHosts":["ironadamant.com"]} as never)),
  "classifySeedReadiness({\"profile\":\"app-example\",\"url\":\"https://app.example\",\"cookies\":2,\"origins\":1,\"sessionSt...)": () => classifySeedReadiness(({"profile":"app-example","url":"https://app.example","cookies":2,"origins":1,"sessionStorage":3,"cookieHosts":["cdn.tracker.test"]} as never)),
  "classifySeedReadiness({\"profile\":\"app-example\",\"url\":\"https://app.example\",\"cookies\":2,\"origins\":1,\"sessionSt...) #2": () => classifySeedReadiness(({"profile":"app-example","url":"https://app.example","cookies":2,"origins":1,"sessionStorage":0,"cookieHosts":["cdn.tracker.test"]} as never)),
  "classifySeedReadiness({\"url\":\"https://app.example\",\"cookies\":3,\"origins\":1,\"sessionStorage\":0,\"cookieHosts\":[...)": () => classifySeedReadiness(({"url":"https://app.example","cookies":3,"origins":1,"sessionStorage":0,"cookieHosts":["app.example"],"appOriginCookieCount":0} as never)),
  "parseAuthKeyNames(\"msal.token, accessToken\")": () => parseAuthKeyNames("msal.token, accessToken"),
  "isSafeAuthKeyName(\"access_token\")": () => isSafeAuthKeyName("access_token"),
  "localStorageAuthKeyNames({\"cookies\":[],\"origins\":[{\"origin\":\"https://app.example\",\"localStorage\":[{\"name\":\"acces...)": () => localStorageAuthKeyNames(({"cookies":[],"origins":[{"origin":"https://app.example","localStorage":[{"name":"accessToken","value":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.payload.sig"},{"name":"__auspex_ss__:accessToken","value":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.payload.sig"},{"name":"theme","value":"dark"}]}]} as never), "https://app.example"),
  "classifySeedReadiness({\"url\":\"https://app.example\",\"cookies\":2,\"origins\":1,\"sessionStorage\":0,\"appOriginCooki...)": () => classifySeedReadiness(({"url":"https://app.example","cookies":2,"origins":1,"sessionStorage":0,"appOriginCookieCount":2} as never)),
  "cookieSaveGuide({\"profile\":\"app-example\",\"readiness\":{\"phase\":\"post-save\",\"appOriginCookies\":true,\"appO...)": () => cookieSaveGuide(({"profile":"app-example","readiness":{"phase":"post-save","appOriginCookies":true,"appOriginCookieCount":2,"localStorageCount":0,"localStorageAuthKeyNames":[],"sessionStorageCount":0,"sessionStorageMiss":true,"idpOnly":false,"weakSeed":false,"shape":"cookie-strong","solariSaveReady":true},"url":"https://app.example/home","expect":"Workspace ready"} as never)),
}
