// Recorded from unit tests by experiments/slim-tests/record-goldens.ts. Outputs live in ../out/fail-closed.json.
import { type GoldenCases } from "../harness.ts"
import { isNoRetryReason, mayRetryCheck, shouldVerifyAfterCheck, shouldVerifyCheck } from "../../../src/fail-closed.ts"

export const cases: GoldenCases = {
  "isNoRetryReason(\"loggedOut\")": () => isNoRetryReason("loggedOut"),
  "isNoRetryReason(\"needsHuman\")": () => isNoRetryReason("needsHuman"),
  "mayRetryCheck(\"loggedOut\")": () => mayRetryCheck("loggedOut"),
  "mayRetryCheck(\"needsHuman\")": () => mayRetryCheck("needsHuman"),
  "shouldVerifyAfterCheck(\"loggedOut\")": () => shouldVerifyAfterCheck("loggedOut"),
  "shouldVerifyAfterCheck(\"needsHuman\")": () => shouldVerifyAfterCheck("needsHuman"),
  "shouldVerifyAfterCheck(\"recordedLoggedIn\")": () => shouldVerifyAfterCheck("recordedLoggedIn"),
  "isNoRetryReason(\"expectMatchedPublicLanding\")": () => isNoRetryReason("expectMatchedPublicLanding"),
  "mayRetryCheck(\"expectMatchedPublicLanding\")": () => mayRetryCheck("expectMatchedPublicLanding"),
  "shouldVerifyAfterCheck(\"expectMatchedPublicLanding\")": () => shouldVerifyAfterCheck("expectMatchedPublicLanding"),
  "isNoRetryReason(\"hostChanged\")": () => isNoRetryReason("hostChanged"),
  "mayRetryCheck(\"hostChanged\")": () => mayRetryCheck("hostChanged"),
  "shouldVerifyAfterCheck(\"hostChanged\")": () => shouldVerifyAfterCheck("hostChanged"),
  "mayRetryCheck(\"matched\")": () => mayRetryCheck("matched"),
  "mayRetryCheck(\"mismatch\")": () => mayRetryCheck("mismatch"),
  "mayRetryCheck(\"network\")": () => mayRetryCheck("network"),
  "shouldVerifyAfterCheck(\"matched\")": () => shouldVerifyAfterCheck("matched"),
  "shouldVerifyAfterCheck(\"mismatch\")": () => shouldVerifyAfterCheck("mismatch"),
  "shouldVerifyCheck({})": () => shouldVerifyCheck(({} as never)),
  "shouldVerifyCheck({\"name\":\"ironadamant\"})": () => shouldVerifyCheck(({"name":"ironadamant"} as never)),
  "shouldVerifyCheck({\"name\":\"consistencyhub\"})": () => shouldVerifyCheck(({"name":"consistencyhub"} as never)),
  "shouldVerifyCheck({\"name\":\"ConsistencyHub\"})": () => shouldVerifyCheck(({"name":"ConsistencyHub"} as never)),
  "shouldVerifyCheck({\"name\":\"consistencyhub\",\"verify\":true})": () => shouldVerifyCheck(({"name":"consistencyhub","verify":true} as never)),
  "shouldVerifyCheck({\"name\":\"consistencyhub\",\"verify\":false})": () => shouldVerifyCheck(({"name":"consistencyhub","verify":false} as never)),
  "shouldVerifyCheck({\"name\":\"consistencyhub\",\"verifyWithProfile\":true})": () => shouldVerifyCheck(({"name":"consistencyhub","verifyWithProfile":true} as never)),
  "shouldVerifyCheck({\"name\":\"consistencyhub\",\"verify\":false,\"verifyWithProfile\":true})": () => shouldVerifyCheck(({"name":"consistencyhub","verify":false,"verifyWithProfile":true} as never)),
  "shouldVerifyCheck({\"name\":\"ironadamant\",\"verify\":false})": () => shouldVerifyCheck(({"name":"ironadamant","verify":false} as never)),
  "shouldVerifyCheck({\"profile\":\"consistencyhub\"})": () => shouldVerifyCheck(({"profile":"consistencyhub"} as never)),
  "shouldVerifyCheck({\"profile\":\"ConsistencyHub\"})": () => shouldVerifyCheck(({"profile":"ConsistencyHub"} as never)),
  "shouldVerifyCheck({\"url\":\"https://onedrive.live.com/\",\"profile\":\"consistencyhub\"})": () => shouldVerifyCheck(({"url":"https://onedrive.live.com/","profile":"consistencyhub"} as never)),
  "shouldVerifyCheck({\"url\":\"https://consistencyhub.io\",\"profile\":\"consistencyhub\"})": () => shouldVerifyCheck(({"url":"https://consistencyhub.io","profile":"consistencyhub"} as never)),
  "shouldVerifyCheck({\"url\":\"https://onedrive.live.com/\",\"profile\":\"other-ms\"})": () => shouldVerifyCheck(({"url":"https://onedrive.live.com/","profile":"other-ms"} as never)),
  "shouldVerifyCheck({\"url\":\"https://ironadamant.com\",\"profile\":\"other-ms\"})": () => shouldVerifyCheck(({"url":"https://ironadamant.com","profile":"other-ms"} as never)),
  "shouldVerifyCheck({\"url\":\"https://onedrive.live.com/\",\"profile\":\"consistencyhub\",\"verify\":true})": () => shouldVerifyCheck(({"url":"https://onedrive.live.com/","profile":"consistencyhub","verify":true} as never)),
  "shouldVerifyCheck({\"url\":\"https://onedrive.live.com/\",\"profile\":\"consistencyhub\",\"verifyWithProfile\":true})": () => shouldVerifyCheck(({"url":"https://onedrive.live.com/","profile":"consistencyhub","verifyWithProfile":true} as never)),
  "shouldVerifyCheck({\"profile\":\"acme\",\"url\":\"https://app.example.com\"})": () => shouldVerifyCheck(({"profile":"acme","url":"https://app.example.com"} as never)),
  "shouldVerifyCheck({\"profile\":\"acme\",\"url\":\"https://ironadamant.com\"})": () => shouldVerifyCheck(({"profile":"acme","url":"https://ironadamant.com"} as never)),
  "shouldVerifyCheck({\"url\":\"https://app.example.com\"})": () => shouldVerifyCheck(({"url":"https://app.example.com"} as never)),
}
