// Recorded from unit tests by experiments/slim-tests/record-goldens.ts. Outputs live in ../out/fold-steer.json.
import { type GoldenCases } from "../harness.ts"
import { foldLeadBlockedByDrain, foldMissFinalizeGuide, idpOnlySaveGuide, isIdpOnlySave, shouldSteerToFinalize } from "../../../src/fold-steer.ts"

export const cases: GoldenCases = {
  "shouldSteerToFinalize({\"editorSave\":{\"ok\":true,\"status\":200},\"editorFold\":{\"ok\":false,\"reason\":\"no-cdp\"},\"coo...)": () => shouldSteerToFinalize(({"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"cookies":4} as never)),
  "foldMissFinalizeGuide({\"profile\":\"app-example\",\"editorSave\":{\"ok\":true,\"status\":200},\"editorFold\":{\"ok\":false...)": () => foldMissFinalizeGuide(({"profile":"app-example","editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"streamNoted":true,"url":"https://app.example/languages","expect":"Your courses"} as never)),
  "isIdpOnlySave({\"editorSave\":{\"ok\":true,\"status\":200},\"editorFold\":{\"ok\":false,\"reason\":\"no-cdp\"},\"coo...)": () => isIdpOnlySave(({"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"cookies":4,"cookieHosts":["live.com","login.live.com","login.microsoft.com","login.microsoftonline.com"],"siteHost":"consistencyhub.io","sessionStorage":0} as never)),
  "isIdpOnlySave({\"editorSave\":{\"ok\":true,\"status\":200},\"editorFold\":{\"ok\":false,\"reason\":\"no-cdp\"},\"coo...) #2": () => isIdpOnlySave(({"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"cookies":4,"cookieHosts":["live.com","login.live.com","login.microsoft.com","login.microsoftonline.com"],"siteHost":"consistencyhub.io","sessionStorage":2} as never)),
  "isIdpOnlySave({\"editorSave\":{\"ok\":true,\"status\":200},\"editorFold\":{\"ok\":false,\"reason\":\"no-cdp\"},\"coo...) #3": () => isIdpOnlySave(({"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"cookies":4,"cookieHosts":["accounts.google.com"],"siteHost":"consistencyhub.io","sessionStorage":0} as never)),
  "shouldSteerToFinalize({\"editorSave\":{\"ok\":true,\"status\":200},\"editorFold\":{\"ok\":false,\"reason\":\"no-cdp\"},\"coo...) #2": () => shouldSteerToFinalize(({"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"cookies":4,"cookieHosts":["live.com","login.live.com","login.microsoft.com","login.microsoftonline.com"],"siteHost":"consistencyhub.io","sessionStorage":0} as never)),
  "idpOnlySaveGuide(\"consistencyhub\")": () => idpOnlySaveGuide("consistencyhub"),
  "idpOnlySaveGuide(\"consistencyhub-io\", {\"liveHost\":\"consistencyhub.io\",\"siteHost\":\"consistencyhub.io\"})": () => idpOnlySaveGuide("consistencyhub-io", ({"liveHost":"consistencyhub.io","siteHost":"consistencyhub.io"} as never)),
  "isIdpOnlySave({\"editorSave\":{\"ok\":true,\"status\":200},\"editorFold\":{\"ok\":false,\"reason\":\"no-cdp\"},\"coo...) #4": () => isIdpOnlySave(({"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"cookies":39,"origins":3,"cookieHosts":["google.com","live.com","login.live.com","login.microsoft.com","login.microsoftonline.com","www.google.com"],"siteHost":"consistencyhub.io","liveHost":"consistencyhub.io","sessionStorage":0} as never)),
  "shouldSteerToFinalize({\"editorSave\":{\"ok\":true,\"status\":200},\"editorFold\":{\"ok\":false,\"reason\":\"no-cdp\"},\"coo...) #3": () => shouldSteerToFinalize(({"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"cookies":39,"origins":3,"cookieHosts":["google.com","live.com","login.live.com","login.microsoft.com","login.microsoftonline.com","www.google.com"],"siteHost":"consistencyhub.io","liveHost":"consistencyhub.io","sessionStorage":0} as never)),
  "isIdpOnlySave({\"editorSave\":{\"ok\":true,\"status\":200},\"editorFold\":{\"ok\":false,\"reason\":\"no-cdp\"},\"coo...) #5": () => isIdpOnlySave(({"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"cookies":39,"origins":3,"cookieHosts":["doubleclick.net","login.microsoftonline.com"],"siteHost":"consistencyhub.io","liveHost":"consistencyhub.io","sessionStorage":0} as never)),
  "shouldSteerToFinalize({\"editorSave\":{\"ok\":true,\"status\":200},\"editorFold\":{\"ok\":false,\"reason\":\"no-cdp\"},\"coo...) #4": () => shouldSteerToFinalize(({"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"cookies":39,"origins":3,"cookieHosts":["doubleclick.net","login.microsoftonline.com"],"siteHost":"consistencyhub.io","liveHost":"consistencyhub.io","sessionStorage":0} as never)),
  "foldLeadBlockedByDrain({\"status\":\"stream-expired\",\"cookieHosts\":[\"google.com\",\"live.com\",\"login.live.com\",\"log...)": () => foldLeadBlockedByDrain(({"status":"stream-expired","cookieHosts":["google.com","live.com","login.live.com","login.microsoft.com","login.microsoftonline.com","www.google.com"],"siteHost":"consistencyhub.io"} as never)),
  "foldLeadBlockedByDrain({\"status\":\"timeout\",\"cookieHosts\":[\"google.com\",\"live.com\",\"login.live.com\",\"login.micr...)": () => foldLeadBlockedByDrain(({"status":"timeout","cookieHosts":["google.com","live.com","login.live.com","login.microsoft.com","login.microsoftonline.com","www.google.com"],"siteHost":"consistencyhub.io"} as never)),
  "foldLeadBlockedByDrain({\"status\":\"stream-expired\",\"cookieHosts\":[\"google.com\",\"live.com\",\"login.live.com\",\"log...) #2": () => foldLeadBlockedByDrain(({"status":"stream-expired","cookieHosts":["google.com","live.com","login.live.com","login.microsoft.com","login.microsoftonline.com","www.google.com","consistencyhub.io"],"siteHost":"consistencyhub.io"} as never)),
  "foldLeadBlockedByDrain({\"status\":\"completed\",\"cookieHosts\":[\"google.com\",\"live.com\",\"login.live.com\",\"login.mi...)": () => foldLeadBlockedByDrain(({"status":"completed","cookieHosts":["google.com","live.com","login.live.com","login.microsoft.com","login.microsoftonline.com","www.google.com"],"siteHost":"consistencyhub.io"} as never)),
  "isIdpOnlySave({\"editorSave\":{\"ok\":true,\"status\":200},\"editorFold\":{\"ok\":false,\"reason\":\"no-cdp\"},\"coo...) #6": () => isIdpOnlySave(({"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"cookies":5,"cookieHosts":["live.com","login.live.com","login.microsoft.com","login.microsoftonline.com","consistencyhub.io"],"siteHost":"consistencyhub.io","sessionStorage":0} as never)),
  "shouldSteerToFinalize({\"editorSave\":{\"ok\":true,\"status\":200},\"editorFold\":{\"ok\":false,\"reason\":\"no-cdp\"},\"coo...) #5": () => shouldSteerToFinalize(({"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"cookies":5,"cookieHosts":["live.com","login.live.com","login.microsoft.com","login.microsoftonline.com","consistencyhub.io"],"siteHost":"consistencyhub.io","sessionStorage":0} as never)),
  "isIdpOnlySave({\"editorSave\":{\"ok\":true,\"status\":200},\"editorFold\":{\"ok\":false,\"reason\":\"no-cdp\"},\"coo...) #7": () => isIdpOnlySave(({"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"cookies":5,"cookieHosts":["cdn.tracker.test"],"siteHost":"consistencyhub.io","sessionStorage":0} as never)),
  "shouldSteerToFinalize({\"editorSave\":{\"ok\":true,\"status\":200},\"editorFold\":{\"ok\":false,\"reason\":\"no-cdp\"},\"coo...) #6": () => shouldSteerToFinalize(({"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"cookies":5,"cookieHosts":["cdn.tracker.test"],"siteHost":"consistencyhub.io","sessionStorage":0} as never)),
  "isIdpOnlySave({\"cookieHosts\":[\"live.com\",\"login.live.com\",\"login.microsoft.com\",\"login.microsoftonlin...)": () => isIdpOnlySave(({"cookieHosts":["live.com","login.live.com","login.microsoft.com","login.microsoftonline.com"],"siteHost":"consistencyhub.io","sessionStorage":0,"cookies":4,"localStorageAuthKeyNames":["accessToken"]} as never)),
  "shouldSteerToFinalize({\"editorSave\":{\"ok\":false,\"status\":401,\"error\":\"Unauthorized\"},\"editorFold\":{\"ok\":false...)": () => shouldSteerToFinalize(({"editorSave":{"ok":false,"status":401,"error":"Unauthorized"},"editorFold":{"ok":false,"reason":"no-cdp"},"cookies":2,"origins":3} as never)),
  "shouldSteerToFinalize({\"editorSave\":{\"ok\":true,\"status\":200},\"editorFold\":{\"ok\":false,\"reason\":\"no-cdp\"},\"coo...) #7": () => shouldSteerToFinalize(({"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"cookies":0,"origins":0} as never)),
  "shouldSteerToFinalize({\"editorSave\":{\"ok\":true,\"status\":200},\"editorFold\":{\"ok\":false,\"reason\":\"no-cdp\"},\"coo...) #8": () => shouldSteerToFinalize(({"editorSave":{"ok":true,"status":200},"editorFold":{"ok":false,"reason":"no-cdp"},"cookies":3,"hostChanged":true} as never)),
}
