// Recorded from unit tests by experiments/slim-tests/record-goldens.ts. Outputs live in ../out/live-host-change.json.
import { type GoldenCases } from "../harness.ts"
import { adviseLiveHostChange, decideLiveHostPersist, doorSaveSiteUrl, httpsPageUrlFromRecord, sameProductAdopt, sameProductHosts } from "../../../src/live-host-change.ts"

export const cases: GoldenCases = {
  "sameProductHosts(\"app.skysql.com\", \"cloud.mariadb.com\")": () => sameProductHosts("app.skysql.com", "cloud.mariadb.com"),
  "sameProductAdopt({\"mintUrl\":\"https://app.skysql.com\",\"pageUrl\":\"https://cloud.mariadb.com/dashboard\"})": () => sameProductAdopt(({"mintUrl":"https://app.skysql.com","pageUrl":"https://cloud.mariadb.com/dashboard"} as never)),
  "adviseLiveHostChange({\"profile\":\"app-skysql-com\",\"mintUrl\":\"https://app.skysql.com\",\"pageUrl\":\"https://cloud...)": () => adviseLiveHostChange(({"profile":"app-skysql-com","mintUrl":"https://app.skysql.com","pageUrl":"https://cloud.mariadb.com/"} as never)),
  "adviseLiveHostChange({\"profile\":\"app-skysql-com\",\"mintUrl\":\"https://app.skysql.com\",\"pageUrl\":\"https://evil....)": () => adviseLiveHostChange(({"profile":"app-skysql-com","mintUrl":"https://app.skysql.com","pageUrl":"https://evil.example/steal"} as never)),
  "doorSaveSiteUrl(\"\", \"https://consistencyhub.io\", \"\")": () => doorSaveSiteUrl("", "https://consistencyhub.io", ""),
  "doorSaveSiteUrl(\"\", \"https://consistencyhub.io\", \"https://app.example/login\")": () => doorSaveSiteUrl("", "https://consistencyhub.io", "https://app.example/login"),
  "doorSaveSiteUrl(\"\", \"http://insecure.example\", \"notaurl\")": () => doorSaveSiteUrl("", "http://insecure.example", "notaurl"),
  "doorSaveSiteUrl(\"https://app.socialaize.com/home?q=1\", \"https://myapp.example/dashboard\", \"https://type...)": () => doorSaveSiteUrl("https://app.socialaize.com/home?q=1", "https://myapp.example/dashboard", "https://typed.example/secret"),
  "adviseLiveHostChange({\"profile\":\"myapp-example\",\"mintUrl\":\"https://myapp.example\",\"pageUrl\":\"https://app.soc...)": () => adviseLiveHostChange(({"profile":"myapp-example","mintUrl":"https://myapp.example","pageUrl":"https://app.socialaize.com/home","state":{"origins":[{"origin":"https://app.socialaize.com","localStorage":[{"name":"token"}]}],"cookies":[{"domain":".app.socialaize.com","name":"sid"}]}} as never)),
  "adviseLiveHostChange({\"profile\":\"myapp-example\",\"mintUrl\":\"https://myapp.example\",\"pageUrl\":\"https://www.mya...)": () => adviseLiveHostChange(({"profile":"myapp-example","mintUrl":"https://myapp.example","pageUrl":"https://www.myapp.example/dashboard"} as never)),
  "adviseLiveHostChange({\"profile\":\"myapp-example\",\"mintUrl\":\"https://myapp.example\",\"pageUrl\":\"https://login.m...)": () => adviseLiveHostChange(({"profile":"myapp-example","mintUrl":"https://myapp.example","pageUrl":"https://login.microsoftonline.com/common","state":{"cookies":[{"domain":"login.microsoftonline.com","name":"ESTSAUTH"}],"origins":[{"origin":"https://myapp.example","localStorage":[{"name":"accessToken"}]}]}} as never)),
  "adviseLiveHostChange({\"profile\":\"consistencyhub\",\"mintUrl\":\"https://consistencyhub.io\",\"pageUrl\":\"https://ap...)": () => adviseLiveHostChange(({"profile":"consistencyhub","mintUrl":"https://consistencyhub.io","pageUrl":"https://app.consistencyhub.io/docs"} as never)),
  "adviseLiveHostChange({\"profile\":\"myapp-example\",\"mintUrl\":\"https://myapp.example\",\"pageUrl\":\"https://myapp.e...)": () => adviseLiveHostChange(({"profile":"myapp-example","mintUrl":"https://myapp.example","pageUrl":"https://myapp.example/app","state":{"cookies":[{"domain":"cdn.myapp.example","name":"a"},{"domain":"cdn.myapp.example","name":"b"}]}} as never)),
  "adviseLiveHostChange({\"profile\":\"myapp-example\",\"mintUrl\":\"https://myapp.example\",\"pageUrl\":\"https://myapp.e...) #2": () => adviseLiveHostChange(({"profile":"myapp-example","mintUrl":"https://myapp.example","pageUrl":"https://myapp.example/dashboard","state":{"origins":[{"origin":"https://app.socialaize.com","localStorage":[{"name":"k"}]}]}} as never)),
  "adviseLiveHostChange({\"profile\":\"app-socialaize-com\",\"mintUrl\":\"https://myapp.example\",\"pageUrl\":\"https://ap...)": () => adviseLiveHostChange(({"profile":"app-socialaize-com","mintUrl":"https://myapp.example","pageUrl":"https://app.socialaize.com/home"} as never)),
  "adviseLiveHostChange({\"profile\":\"work\",\"mintUrl\":\"https://myapp.example\",\"pageUrl\":\"https://myapp.example/ho...)": () => adviseLiveHostChange(({"profile":"work","mintUrl":"https://myapp.example","pageUrl":"https://myapp.example/home"} as never)),
  "adviseLiveHostChange({\"profile\":\"work\",\"mintUrl\":\"https://myapp.example\",\"pageUrl\":\"https://app.socialaize.c...)": () => adviseLiveHostChange(({"profile":"work","mintUrl":"https://myapp.example","pageUrl":"https://app.socialaize.com/home"} as never)),
  "adviseLiveHostChange({\"profile\":\"consistencyhub\",\"pageUrl\":\"https://app.socialaize.com/home\"})": () => adviseLiveHostChange(({"profile":"consistencyhub","pageUrl":"https://app.socialaize.com/home"} as never)),
  "adviseLiveHostChange({\"profile\":\"work\",\"pageUrl\":\"https://app.socialaize.com/home\"})": () => adviseLiveHostChange(({"profile":"work","pageUrl":"https://app.socialaize.com/home"} as never)),
  "decideLiveHostPersist({\"profile\":\"consistencyhub\",\"mintUrl\":\"https://consistencyhub.io\",\"pageUrl\":\"https://on...)": () => decideLiveHostPersist(({"profile":"consistencyhub","mintUrl":"https://consistencyhub.io","pageUrl":"https://onedrive.live.com/","enforceDetect":false} as never)),
  "decideLiveHostPersist({\"profile\":\"consistencyhub\",\"mintUrl\":\"https://consistencyhub.io\",\"pageUrl\":\"https://on...) #2": () => decideLiveHostPersist(({"profile":"consistencyhub","mintUrl":"https://consistencyhub.io","pageUrl":"https://onedrive.live.com/","enforceDetect":true} as never)),
  "decideLiveHostPersist({\"profile\":\"myapp-example\",\"mintUrl\":\"https://myapp.example\",\"pageUrl\":\"https://myapp.e...)": () => decideLiveHostPersist(({"profile":"myapp-example","mintUrl":"https://myapp.example","pageUrl":"https://myapp.example/home","marker":{"suggestedProfile":"app-socialaize-com","suggestedUrl":"https://app.socialaize.com"},"enforceDetect":false} as never)),
  "doorSaveSiteUrl(\"https://app.socialaize.com/a?x=1\", \"https://myapp.example/b\", \"https://evil.example/se...)": () => doorSaveSiteUrl("https://app.socialaize.com/a?x=1", "https://myapp.example/b", "https://evil.example/secret"),
  "doorSaveSiteUrl(\"http://insecure.example\", \"https://myapp.example/dashboard\", \"https://typed.example\")": () => doorSaveSiteUrl("http://insecure.example", "https://myapp.example/dashboard", "https://typed.example"),
  "doorSaveSiteUrl(\"https://user:pass@app.socialaize.com/a\", \"https://myapp.example\")": () => doorSaveSiteUrl("https://user:pass@app.socialaize.com/a", "https://myapp.example"),
  "httpsPageUrlFromRecord({\"url\":\"https://app.socialaize.com\"})": () => httpsPageUrlFromRecord(({"url":"https://app.socialaize.com"} as never)),
  "httpsPageUrlFromRecord({\"pageUrl\":\"https://login.microsoftonline.com/common\"})": () => httpsPageUrlFromRecord(({"pageUrl":"https://login.microsoftonline.com/common"} as never)),
  "httpsPageUrlFromRecord({\"pageUrl\":\"https://app.socialaize.com/path?q=1\"})": () => httpsPageUrlFromRecord(({"pageUrl":"https://app.socialaize.com/path?q=1"} as never)),
}
