// Recorded from unit tests by experiments/slim-tests/record-goldens.ts. Outputs live in ../out/login-trace.json.
import { at, type GoldenCases } from "../harness.ts"
import { cookieHostIsIdp, cookieHostsFromState, foldedExpiresInSecFromState, idpCookiesFromHosts, loginTraceSeedExtras, sanitizeLoginTraceEvent, summarizeLoginTrace, traceUrlParts } from "../../../src/login-trace.ts"

export const cases: GoldenCases = {
  "cookieHostIsIdp(\"google.com\")": at(1790991896455, () => cookieHostIsIdp("google.com")),
  "cookieHostIsIdp(\"www.google.com\")": at(1790991896455, () => cookieHostIsIdp("www.google.com")),
  "cookieHostIsIdp(\"mail.google.com\")": at(1790991896455, () => cookieHostIsIdp("mail.google.com")),
  "cookieHostIsIdp(\".google.com\")": at(1790991896455, () => cookieHostIsIdp(".google.com")),
  "cookieHostsFromState({\"cookies\":[{\"name\":\"sid\",\"value\":\"SECRET\",\"domain\":\".login.microsoftonline.com\"},{\"nam...)": at(1790991897596, () => cookieHostsFromState(({"cookies":[{"name":"sid","value":"SECRET","domain":".login.microsoftonline.com"},{"name":"sid","value":"SECRET","domain":"login.microsoftonline.com"},{"name":"app","value":"x","domain":"consistencyhub.io"}],"origins":[]} as never))),
  "idpCookiesFromHosts(([\"consistencyhub.io\",\"login.microsoftonline.com\"]))": at(1790991897597, () => idpCookiesFromHosts((["consistencyhub.io","login.microsoftonline.com"] as never))),
  "idpCookiesFromHosts(([\"consistencyhub.io\"]))": at(1790991897597, () => idpCookiesFromHosts((["consistencyhub.io"] as never))),
  "idpCookiesFromHosts(([\"login.microsoft.com\"]))": at(1790991897597, () => idpCookiesFromHosts((["login.microsoft.com"] as never))),
  "idpCookiesFromHosts(([\"live.com\"]))": at(1790991897597, () => idpCookiesFromHosts((["live.com"] as never))),
  "idpCookiesFromHosts(([\"onedrive.live.com\"]))": at(1790991897597, () => idpCookiesFromHosts((["onedrive.live.com"] as never))),
  "loginTraceSeedExtras({\"cookies\":[{\"name\":\"ESTSAUTH\",\"value\":\"SECRET\",\"domain\":\"login.microsoftonline.com\"}],...)": at(1790991897598, () => loginTraceSeedExtras(({"cookies":[{"name":"ESTSAUTH","value":"SECRET","domain":"login.microsoftonline.com"}],"origins":[{"origin":"https://consistencyhub.io","localStorage":[{"name":"__auspex_ss__:accessToken","value":"tok"},{"name":"__auspex_ss__:expiresOn","value":"1790991837598"}]}]} as never), "https://consistencyhub.io")),
  "foldedExpiresInSecFromState({\"cookies\":[],\"origins\":[]}, \"https://consistencyhub.io\")": at(1790991897598, () => foldedExpiresInSecFromState(({"cookies":[],"origins":[]} as never), "https://consistencyhub.io")),
  "traceUrlParts(\"https://login.microsoftonline.com/common/oauth2/v2.0/authorize?code_challenge=SECRET&p...)": at(1790991897598, () => traceUrlParts("https://login.microsoftonline.com/common/oauth2/v2.0/authorize?code_challenge=SECRET&prompt=select_account")),
  "sanitizeLoginTraceEvent({\"ts\":\"t\",\"event\":\"login\",\"profile\":\"consistencyhub\",\"sessionId\":\"should-drop\",\"excerpt...)": at(1790991897598, () => sanitizeLoginTraceEvent(({"ts":"t","event":"login","profile":"consistencyhub","sessionId":"should-drop","excerpt":"nope","expiresAt":"2026-09-21T05:46:42.026Z"} as never))),
  "summarizeLoginTrace(([{\"ts\":\"t\",\"event\":\"login\",\"profile\":\"consistencyhub\",\"phoneDoor\":\"ime\",\"remintIndex\":...)": at(1790991897599, () => summarizeLoginTrace(([{"ts":"t","event":"login","profile":"consistencyhub","phoneDoor":"ime","remintIndex":1,"episodeId":"ep-1","mintStage":"ready","urlPresent":true,"vncMintOk":true}] as never))),
  "summarizeLoginTrace(([{\"ts\":\"t\",\"event\":\"login\",\"profile\":\"consistencyhub\",\"phoneDoor\":\"ime\",\"computerDoor\"...)": at(1790991897599, () => summarizeLoginTrace(([{"ts":"t","event":"login","profile":"consistencyhub","phoneDoor":"ime","computerDoor":"desktop-page","remintIndex":1,"episodeId":"ep-desk","mintStage":"ready","urlPresent":true,"vncMintOk":true}] as never))),
  "summarizeLoginTrace(([{\"ts\":\"t\",\"event\":\"login\",\"profile\":\"x\",\"mintStage\":\"key-check\",\"solariCode\":\"Missing...)": at(1790991897599, () => summarizeLoginTrace(([{"ts":"t","event":"login","profile":"x","mintStage":"key-check","solariCode":"MissingApiKey","remintIndex":1}] as never))),
  "summarizeLoginTrace(([{\"ts\":\"t\",\"event\":\"login\",\"profile\":\"x\",\"editorStartStatus\":401,\"mintStage\":\"editor-s...)": at(1790991897599, () => summarizeLoginTrace(([{"ts":"t","event":"login","profile":"x","editorStartStatus":401,"mintStage":"editor-start","remintIndex":1}] as never))),
  "summarizeLoginTrace(([{\"ts\":\"t\",\"event\":\"login\",\"profile\":\"x\",\"editorStartStatus\":409,\"mintStage\":\"editor-s...)": at(1790991897599, () => summarizeLoginTrace(([{"ts":"t","event":"login","profile":"x","editorStartStatus":409,"mintStage":"editor-start","remintIndex":2}] as never))),
  "summarizeLoginTrace(([{\"ts\":\"t\",\"event\":\"login\",\"profile\":\"x\",\"editorStartStatus\":409,\"mintStage\":\"ready\",\"...)": at(1790991897600, () => summarizeLoginTrace(([{"ts":"t","event":"login","profile":"x","editorStartStatus":409,"mintStage":"ready","vncMintOk":true,"phoneDoor":"ime","computerDoor":"desktop-page","remintIndex":1}] as never))),
  "summarizeLoginTrace(([{\"ts\":\"t\",\"event\":\"login\",\"profile\":\"x\",\"mintStage\":\"ready\",\"urlPresent\":true,\"vncMin...)": at(1790991897600, () => summarizeLoginTrace(([{"ts":"t","event":"login","profile":"x","mintStage":"ready","urlPresent":true,"vncMintOk":true,"hostKind":"cluster-internal","remintIndex":1}] as never))),
  "summarizeLoginTrace(([{\"ts\":\"t\",\"event\":\"login\",\"profile\":\"x\",\"mintStage\":\"editor-token\",\"vncMintOk\":false,...)": at(1790991897600, () => summarizeLoginTrace(([{"ts":"t","event":"login","profile":"x","mintStage":"editor-token","vncMintOk":false,"editorStartStatus":200,"tokenTries":20,"remintIndex":1}] as never))),
  "summarizeLoginTrace(([{\"ts\":\"t\",\"event\":\"login\",\"profile\":\"x\",\"mintStage\":\"editor-token\",\"vncMintOk\":false,...) #2": at(1790991897600, () => summarizeLoginTrace(([{"ts":"t","event":"login","profile":"x","mintStage":"editor-token","vncMintOk":false,"editorStartStatus":0,"tokenTries":0,"phoneDoor":"none","remintIndex":1,"episodeId":"ep-empty"}] as never))),
  "summarizeLoginTrace(([{\"ts\":\"t\",\"event\":\"login\",\"profile\":\"x\",\"mintStage\":\"ready\",\"vncMintOk\":false,\"urlPre...)": at(1790991897600, () => summarizeLoginTrace(([{"ts":"t","event":"login","profile":"x","mintStage":"ready","vncMintOk":false,"urlPresent":true,"phoneDoor":"none","remintIndex":1}] as never))),
  "summarizeLoginTrace(([{\"ts\":\"t\",\"event\":\"login\",\"profile\":\"app-example\",\"solariStatus\":402,\"solariCode\":\"Fe...)": at(1790991897600, () => summarizeLoginTrace(([{"ts":"t","event":"login","profile":"app-example","solariStatus":402,"solariCode":"FeatureRequiresPlan"}] as never))),
  "summarizeLoginTrace(([{\"ts\":\"t\",\"event\":\"login\",\"profile\":\"consistencyhub\",\"solariStatus\":429,\"solariCode\":...)": at(1790991897600, () => summarizeLoginTrace(([{"ts":"t","event":"login","profile":"consistencyhub","solariStatus":429,"solariCode":"ConcurrencyLimitExceeded"}] as never))),
  "summarizeLoginTrace(([{\"ts\":\"t\",\"event\":\"login\",\"profile\":\"consistencyhub\",\"solariStatus\":503,\"solariCode\":...)": at(1790991897600, () => summarizeLoginTrace(([{"ts":"t","event":"login","profile":"consistencyhub","solariStatus":503,"solariCode":"SolariInfraTransient"}] as never))),
}
