// Recorded from unit tests by experiments/slim-tests/record-goldens.ts. Outputs live in ../out/operator-session.json.
import { at, type GoldenCases } from "../harness.ts"
import { decideOperatorSession, decodePhoneSavedList, phoneSavedParams, voluntaryPurgeHonesty } from "../../../src/operator-session.ts"

export const cases: GoldenCases = {
  "decideOperatorSession({\"profiles\":[{\"profile\":\"supabase-com\",\"site\":\"https://supabase.com/dashboard\",\"lastUse...)": at(1790991897763, () => decideOperatorSession(({"profiles":[{"profile":"supabase-com","site":"https://supabase.com/dashboard","lastUsedMs":1700000000000,"username":"fixture-operator-username","password":"fixture-operator-password","solariKey":"slr_live_fixture_operator_key"}],"nowMs":1700000240000,"humanAgree":false,"voluntary":["supabase-com"],"username":"fixture-operator-username","password":"fixture-operator-password","solariKey":"slr_live_fixture_operator_key"} as never))),
  "decideOperatorSession({\"profiles\":[{\"profile\":\"supabase-com\",\"site\":\"https://supabase.com/dashboard\",\"lastUse...) #2": at(1790991897769, () => decideOperatorSession(({"profiles":[{"profile":"supabase-com","site":"https://supabase.com/dashboard","lastUsedMs":1700000000000,"username":"fixture-operator-username","password":"fixture-operator-password","solariKey":"slr_live_fixture_operator_key"},{"profile":"appwrite-io","site":"https://appwrite.io/","lastUsedMs":1700001740000,"username":"fixture-operator-username","password":"fixture-operator-password","solariKey":"slr_live_fixture_operator_key"}],"nowMs":1700001800000,"humanAgree":false,"username":"fixture-operator-username","password":"fixture-operator-password","solariKey":"slr_live_fixture_operator_key"} as never))),
  "decideOperatorSession({\"profiles\":[{\"profile\":\"supabase-com\",\"site\":\"https://supabase.com/dashboard\",\"lastUse...) #3": at(1790991897770, () => decideOperatorSession(({"profiles":[{"profile":"supabase-com","site":"https://supabase.com/dashboard","lastUsedMs":1700000000000,"inUse":true,"password":"fixture-operator-password"}],"nowMs":1700001800000,"humanAgree":false} as never))),
  "decideOperatorSession({\"profiles\":[{\"profile\":\"console-neon-tech\",\"site\":\"https://console.neon.tech\",\"lastUse...)": at(1790991897771, () => decideOperatorSession(({"profiles":[{"profile":"console-neon-tech","site":"https://console.neon.tech","lastUsedMs":1700000240000,"username":"fixture-operator-username","password":"fixture-operator-password","solariKey":"slr_live_fixture_operator_key"}],"nowMs":1700000240000,"voluntary":["console-neon-tech"],"username":"fixture-operator-username","password":"fixture-operator-password","solariKey":"slr_live_fixture_operator_key","humanAgree":false} as never))),
  "decideOperatorSession({\"profiles\":[{\"profile\":\"console-neon-tech\",\"site\":\"https://console.neon.tech\",\"lastUse...) #2": at(1790991897771, () => decideOperatorSession(({"profiles":[{"profile":"console-neon-tech","site":"https://console.neon.tech","lastUsedMs":1700000240000,"username":"fixture-operator-username","password":"fixture-operator-password","solariKey":"slr_live_fixture_operator_key"}],"nowMs":1700000240000,"voluntary":["console-neon-tech"],"username":"fixture-operator-username","password":"fixture-operator-password","solariKey":"slr_live_fixture_operator_key","humanAgree":true} as never))),
  "phoneSavedParams(([{\"profile\":\"socialaize-com\",\"site\":\"https://socialaize.com/login\",\"username\":\"fixture...)": at(1790991897771, () => phoneSavedParams(([{"profile":"socialaize-com","site":"https://socialaize.com/login","username":"fixture-operator-username","password":"fixture-operator-password"}] as never), 1700000000000)),
  "decodePhoneSavedList(\"W3sic2l0ZSI6Imh0dHBzOi8vc29jaWFsYWl6ZS5jb20vbG9naW4iLCJwcm9maWxlIjoic29jaWFsYWl6ZS1jb2...)": at(1790991897772, () => decodePhoneSavedList("W3sic2l0ZSI6Imh0dHBzOi8vc29jaWFsYWl6ZS5jb20vbG9naW4iLCJwcm9maWxlIjoic29jaWFsYWl6ZS1jb20ifV0")),
  "voluntaryPurgeHonesty({\"purge\":\"hub\",\"humanAgree\":true,\"wiped\":[],\"wipeFailed\":[{\"name\":\"hub\",\"error\":\"409 ed...)": at(1790991897772, () => voluntaryPurgeHonesty(({"purge":"hub","humanAgree":true,"wiped":[],"wipeFailed":[{"name":"hub","error":"409 editor is open"}]} as never))),
  "voluntaryPurgeHonesty({\"purge\":\"hub\",\"humanAgree\":true,\"wiped\":[]})": at(1790991897773, () => voluntaryPurgeHonesty(({"purge":"hub","humanAgree":true,"wiped":[]} as never))),
  "voluntaryPurgeHonesty({\"wiped\":[]})": at(1790991897777, () => voluntaryPurgeHonesty(({"wiped":[]} as never))),
  "voluntaryPurgeHonesty({\"purge\":\"hub\",\"humanAgree\":true,\"wiped\":[\"hub\"]})": at(1790991897777, () => voluntaryPurgeHonesty(({"purge":"hub","humanAgree":true,"wiped":["hub"]} as never))),
}
