// Recorded from unit tests by experiments/slim-tests/record-goldens.ts. Outputs live in ../out/profile-host-advice.json.
import { type GoldenCases } from "../harness.ts"
import { adviseProfileHost, stampLoginHost, stampProfileHostAdvice } from "../../../src/profile-host-advice.ts"

export const cases: GoldenCases = {
  "adviseProfileHost({\"profile\":\"App-Example-Com\",\"url\":\"https://app.example.com/dashboard\"})": () => adviseProfileHost(({"profile":"App-Example-Com","url":"https://app.example.com/dashboard"} as never)),
  "adviseProfileHost({\"profile\":\"example-com\",\"url\":\"https://www.example.com\"})": () => adviseProfileHost(({"profile":"example-com","url":"https://www.example.com"} as never)),
  "adviseProfileHost({\"profile\":\"ConsistencyHub\",\"url\":\"https://www.consistencyhub.io/login\"})": () => adviseProfileHost(({"profile":"ConsistencyHub","url":"https://www.consistencyhub.io/login"} as never)),
  "adviseProfileHost({\"profile\":\"consistencyhub\",\"url\":\"https://app.consistencyhub.io\"})": () => adviseProfileHost(({"profile":"consistencyhub","url":"https://app.consistencyhub.io"} as never)),
  "stampLoginHost({\"profileId\":\"p\",\"name\":\"consistencyhub\",\"consoleUrl\":\"https://console.getsolari.com\",\"...)": () => stampLoginHost(({"profileId":"p","name":"consistencyhub","consoleUrl":"https://console.getsolari.com","handoff":{"url":"https://console.getsolari.com/handoff/abc","mobileUrl":"https://console.getsolari.com/handoff/abc","openOnPhone":"Solari handoff is noVNC (a picture of Chrome). The phone software keyboard will not open there. Remint auspex_login for the Auspex phone page. Never type in Solari's remote Chromium / noVNC card on a phone: that stream is a picture of Chrome, so the phone software keyboard will not open. Auspex phone.html is a seed/handoff door for off-site typing (IME + Save paste), not a same-session VNC takeover of the agent's live check. Never paste the password into chat.","oneLiner":"Auspex login (phone): https://console.getsolari.com/handoff/abc","streamExpirySource":"unknown"},"url":"https://console.getsolari.com/handoff/abc","handoffId":"h1","expiresAt":"soon","sinceVersion":3,"next":"Solari handoff is noVNC (a picture of Chrome). The phone software keyboard will not open there. Remint auspex_login for the Auspex phone page. If cookies or cache are cleared, or the remote session or saved profile is wiped, type the login again. Auspex and ironadamant.com do not host those credentials or session secrets; they live only in the remote Chrome session and on the destination site. Never paste or type the password through the agent. Never type in Solari's remote Chromium / noVNC card on a phone: that stream is a picture of Chrome, so the phone software keyboard will not open. Auspex phone.html is a seed/handoff door for off-site typing (IME + Save paste), not a same-session VNC takeover of the agent's live check. Sign in at https://consistencyhub.io/login. Then auspex_await_login --profile consistencyhub with saveEditor true (waits up to 30 minutes), then auspex_finalize_login --profile consistencyhub (pass --url and --expect unless a saved check), then auspex_check --profile consistencyhub. Do not skip finalize-login after Save. Off-site: remint auspex_login for the phone page. If the handoff Chromium card is blank or spinning for more than 2 to 3 minutes, refresh once; if it stays unresponsive, remint with auspex_login (new handoff URL). Complete IdP consent in the handoff card before Save; do not open parallel agent checks mid-consent.","nextCall":{"tool":"auspex_await_login","saveEditor":true,"profile":"consistencyhub"}} as never), "https://consistencyhub.io/login"),
  "stampProfileHostAdvice({\"ok\":true,\"next\":\"Show handoff.url then auspex_await_login --profile consistencyhub.\",...)": () => stampProfileHostAdvice(({"ok":true,"next":"Show handoff.url then auspex_await_login --profile consistencyhub.","nextCall":{"tool":"auspex_await_login","profile":"consistencyhub","saveEditor":true}} as never), ({"profile":"consistencyhub","url":"https://app.socialaize.com/login"} as never)),
  "stampProfileHostAdvice({\"ok\":true,\"next\":\"Profile host mismatch: --profile consistencyhub is not the host slug...)": () => stampProfileHostAdvice(({"ok":true,"next":"Profile host mismatch: --profile consistencyhub is not the host slug for https://app.socialaize.com/login (suggestedProfile app-socialaize-com). profileHostMatch is false. Do not reuse this profile for the new host. Remint with npx auspex login --profile app-socialaize-com --url https://app.socialaize.com/login (or omit --profile and let the host slug win). This command still ran (soft advise, not a refuse). Do not follow later steps that pass --profile consistencyhub for this host. Show handoff.url then auspex_await_login --profile consistencyhub.","nextCall":{"tool":"auspex_login","profile":"app-socialaize-com","url":"https://app.socialaize.com/login"},"profileHostMatch":false,"suggestedProfile":"app-socialaize-com"} as never), ({"profile":"consistencyhub","url":"https://app.socialaize.com/login"} as never)),
  "adviseProfileHost({\"profile\":\"consistencyhub\",\"url\":\"https://notconsistencyhub.io\"})": () => adviseProfileHost(({"profile":"consistencyhub","url":"https://notconsistencyhub.io"} as never)),
  "adviseProfileHost({\"profile\":\"consistencyhub\",\"url\":\"https://consistencyhub.io.evil.com\"})": () => adviseProfileHost(({"profile":"consistencyhub","url":"https://consistencyhub.io.evil.com"} as never)),
  "adviseProfileHost({\"profile\":\"consistencyhub\",\"url\":\"https://onedrive.live.com/\"})": () => adviseProfileHost(({"profile":"consistencyhub","url":"https://onedrive.live.com/"} as never)),
  "adviseProfileHost({\"profile\":\"consistencyhub\"})": () => adviseProfileHost(({"profile":"consistencyhub"} as never)),
  "adviseProfileHost({\"url\":\"https://app.example.com\"})": () => adviseProfileHost(({"url":"https://app.example.com"} as never)),
  "adviseProfileHost({\"profile\":\"consistencyhub\",\"url\":\"not-a-url\"})": () => adviseProfileHost(({"profile":"consistencyhub","url":"not-a-url"} as never)),
  "stampLoginHost({\"profileId\":\"p\",\"name\":\"consistencyhub\",\"consoleUrl\":\"https://console.getsolari.com\",\"...) #2": () => stampLoginHost(({"profileId":"p","name":"consistencyhub","consoleUrl":"https://console.getsolari.com","handoff":{"url":"https://console.getsolari.com/handoff/abc","mobileUrl":"https://console.getsolari.com/handoff/abc","openOnPhone":"Solari handoff is noVNC (a picture of Chrome). The phone software keyboard will not open there. Remint auspex_login for the Auspex phone page. Never type in Solari's remote Chromium / noVNC card on a phone: that stream is a picture of Chrome, so the phone software keyboard will not open. Auspex phone.html is a seed/handoff door for off-site typing (IME + Save paste), not a same-session VNC takeover of the agent's live check. Never paste the password into chat.","oneLiner":"Auspex login (phone): https://console.getsolari.com/handoff/abc","streamExpirySource":"unknown"},"url":"https://console.getsolari.com/handoff/abc","handoffId":"h1","expiresAt":"soon","sinceVersion":3,"next":"Solari handoff is noVNC (a picture of Chrome). The phone software keyboard will not open there. Remint auspex_login for the Auspex phone page. If cookies or cache are cleared, or the remote session or saved profile is wiped, type the login again. Auspex and ironadamant.com do not host those credentials or session secrets; they live only in the remote Chrome session and on the destination site. Never paste or type the password through the agent. Never type in Solari's remote Chromium / noVNC card on a phone: that stream is a picture of Chrome, so the phone software keyboard will not open. Auspex phone.html is a seed/handoff door for off-site typing (IME + Save paste), not a same-session VNC takeover of the agent's live check. Sign in. Then auspex_await_login --profile consistencyhub with saveEditor true (waits up to 30 minutes), then auspex_finalize_login --profile consistencyhub (pass --url and --expect unless a saved check), then auspex_check --profile consistencyhub. Do not skip finalize-login after Save. Off-site: remint auspex_login for the phone page. If the handoff Chromium card is blank or spinning for more than 2 to 3 minutes, refresh once; if it stays unresponsive, remint with auspex_login (new handoff URL). Complete IdP consent in the handoff card before Save; do not open parallel agent checks mid-consent.","nextCall":{"tool":"auspex_await_login","saveEditor":true,"profile":"consistencyhub"}} as never), undefined),
  "adviseProfileHost({\"profile\":\"consistencyhub\",\"url\":\"https://consistencyhub.io\"})": () => adviseProfileHost(({"profile":"consistencyhub","url":"https://consistencyhub.io"} as never)),
  "adviseProfileHost({\"profile\":\"consistencyhub\",\"url\":\"https://app.socialaize.com\"})": () => adviseProfileHost(({"profile":"consistencyhub","url":"https://app.socialaize.com"} as never)),
}
