// Recorded from unit tests by experiments/slim-tests/record-goldens.ts. Outputs live in ../out/sweep.json.
import { at, type GoldenCases } from "../harness.ts"
import { classifySweepReceipt, parseSweepPlan } from "../../../src/sweep.ts"

export const cases: GoldenCases = {
  "parseSweepPlan({\"name\":\"App nightly\",\"profile\":\"app-example-com\",\"keepProfile\":true,\"pages\":[{\"name\":\"...)": at(1790991898616, () => parseSweepPlan(({"name":"App nightly","profile":"app-example-com","keepProfile":true,"pages":[{"name":"Projects","url":"https://app.example.com/projects","expect":"Your projects"},{"name":"Billing","url":"https://app.example.com/billing","expect":"Current plan"},{"name":"Team","url":"https://www.app.example.com/team","expect":"Members"}]} as never))),
  "parseSweepPlan({\"pages\":[{\"url\":\"https://example.com/docs/\",\"expect\":\"Docs\"}]})": at(1790991898619, () => parseSweepPlan(({"pages":[{"url":"https://example.com/docs/","expect":"Docs"}]} as never))),
  "parseSweepPlan({\"profile\":\"p\",\"keepProfile\":false,\"pages\":[{\"url\":\"https://a.com/x\",\"expect\":\"X\"}]})": at(1790991898619, () => parseSweepPlan(({"profile":"p","keepProfile":false,"pages":[{"url":"https://a.com/x","expect":"X"}]} as never))),
  "classifySweepReceipt({\"name\":\"home\",\"url\":\"https://app.example/\",\"expect\":\"Workspace ready\"}, {\"schemaVersio...)": at(1790991898621, () => classifySweepReceipt(({"name":"home","url":"https://app.example/","expect":"Workspace ready"} as never), ({"schemaVersion":1,"ok":false,"reason":"mismatch","url":"https://app.example.com/a","expect":"Your projects","screenshotPath":"~/.auspex/runs/s/screenshot.png","excerpt":"SECRET-LOGGED-IN-PAGE-TEXT account 12345678","verify":{"ok":true,"claimOk":false,"errors":[],"claimErrors":[],"anonymousClaimSkipped":true,"claimOkProfile":true,"runDir":"x"},"matched":false,"botWall":true,"diff":{"previousReason":"matched","previousExpect":"Workspace ready"}} as never), true)),
  "classifySweepReceipt({\"name\":\"Projects\",\"url\":\"https://app.example.com/projects\",\"expect\":\"Your projects\"}, ...)": at(1790991898621, () => classifySweepReceipt(({"name":"Projects","url":"https://app.example.com/projects","expect":"Your projects"} as never), ({"schemaVersion":1,"ok":true,"reason":"matched","url":"https://app.example.com/a","expect":"Your projects","screenshotPath":"~/.auspex/runs/s/screenshot.png","excerpt":"SECRET-LOGGED-IN-PAGE-TEXT account 12345678","verify":{"ok":true,"claimOk":false,"errors":[],"claimErrors":[],"anonymousClaimSkipped":true,"claimOkProfile":true,"runDir":"x"}} as never), true)),
  "classifySweepReceipt({\"name\":\"Projects\",\"url\":\"https://app.example.com/projects\",\"expect\":\"Your projects\"}, ...) #2": at(1790991898621, () => classifySweepReceipt(({"name":"Projects","url":"https://app.example.com/projects","expect":"Your projects"} as never), ({"schemaVersion":1,"ok":true,"reason":"matched","url":"https://app.example.com/a","expect":"Your projects","screenshotPath":"~/.auspex/runs/s/screenshot.png","excerpt":"SECRET-LOGGED-IN-PAGE-TEXT account 12345678","verify":{"ok":true,"claimOk":false,"errors":[],"claimErrors":[],"claimOkProfile":false,"runDir":"x"}} as never), true)),
  "classifySweepReceipt({\"name\":\"Projects\",\"url\":\"https://app.example.com/projects\",\"expect\":\"Your projects\"}, ...) #3": at(1790991898621, () => classifySweepReceipt(({"name":"Projects","url":"https://app.example.com/projects","expect":"Your projects"} as never), ({"schemaVersion":1,"ok":true,"reason":"matched","url":"https://app.example.com/a","expect":"Your projects","screenshotPath":"~/.auspex/runs/s/screenshot.png","excerpt":"SECRET-LOGGED-IN-PAGE-TEXT account 12345678"} as never), true)),
  "classifySweepReceipt({\"name\":\"Projects\",\"url\":\"https://app.example.com/projects\",\"expect\":\"Your projects\"}, ...) #4": at(1790991898621, () => classifySweepReceipt(({"name":"Projects","url":"https://app.example.com/projects","expect":"Your projects"} as never), ({"schemaVersion":1,"ok":true,"reason":"matched","url":"https://app.example.com/a","expect":"Your projects","screenshotPath":"~/.auspex/runs/s/screenshot.png","excerpt":"SECRET-LOGGED-IN-PAGE-TEXT account 12345678"} as never), false)),
  "classifySweepReceipt({\"name\":\"Projects\",\"url\":\"https://app.example.com/projects\",\"expect\":\"Your projects\"}, ...) #5": at(1790991898621, () => classifySweepReceipt(({"name":"Projects","url":"https://app.example.com/projects","expect":"Your projects"} as never), ({"schemaVersion":1,"ok":false,"reason":"mismatch","url":"https://app.example.com/a","expect":"Your projects","screenshotPath":"~/.auspex/runs/s/screenshot.png","excerpt":"SECRET-LOGGED-IN-PAGE-TEXT account 12345678","verify":{"ok":true,"claimOk":false,"errors":[],"claimErrors":[],"anonymousClaimSkipped":true,"claimOkProfile":false,"runDir":"x"},"matched":false} as never), true)),
  "classifySweepReceipt({\"name\":\"Projects\",\"url\":\"https://app.example.com/projects\",\"expect\":\"Your projects\"}, ...) #6": at(1790991898621, () => classifySweepReceipt(({"name":"Projects","url":"https://app.example.com/projects","expect":"Your projects"} as never), ({"schemaVersion":1,"ok":false,"reason":"mismatch","url":"https://app.example.com/a","expect":"Your projects","screenshotPath":"~/.auspex/runs/s/screenshot.png","excerpt":"SECRET-LOGGED-IN-PAGE-TEXT account 12345678","verify":{"ok":true,"claimOk":false,"errors":[],"claimErrors":[],"anonymousClaimSkipped":true,"claimOkProfile":true,"runDir":"x"},"matched":true} as never), false)),
  "classifySweepReceipt({\"name\":\"Projects\",\"url\":\"https://app.example.com/projects\",\"expect\":\"Your projects\"}, ...) #7": at(1790991898621, () => classifySweepReceipt(({"name":"Projects","url":"https://app.example.com/projects","expect":"Your projects"} as never), ({"schemaVersion":1,"ok":false,"reason":"network","url":"https://app.example.com/a","expect":"Your projects","screenshotPath":"~/.auspex/runs/s/screenshot.png","excerpt":"SECRET-LOGGED-IN-PAGE-TEXT account 12345678","verify":{"ok":true,"claimOk":false,"errors":[],"claimErrors":[],"anonymousClaimSkipped":true,"claimOkProfile":true,"runDir":"x"}} as never), true)),
  "classifySweepReceipt({\"name\":\"Projects\",\"url\":\"https://app.example.com/projects\",\"expect\":\"Your projects\"}, ...) #8": at(1790991898621, () => classifySweepReceipt(({"name":"Projects","url":"https://app.example.com/projects","expect":"Your projects"} as never), ({"schemaVersion":1,"ok":false,"reason":"loggedOut","url":"https://app.example.com/a","expect":"Your projects","screenshotPath":"~/.auspex/runs/s/screenshot.png","excerpt":"SECRET-LOGGED-IN-PAGE-TEXT account 12345678","verify":{"ok":true,"claimOk":false,"errors":[],"claimErrors":[],"anonymousClaimSkipped":true,"claimOkProfile":true,"runDir":"x"}} as never), true)),
  "classifySweepReceipt({\"name\":\"Projects\",\"url\":\"https://app.example.com/projects\",\"expect\":\"Your projects\"}, ...) #9": at(1790991898621, () => classifySweepReceipt(({"name":"Projects","url":"https://app.example.com/projects","expect":"Your projects"} as never), ({"schemaVersion":1,"ok":false,"reason":"mismatch","url":"https://app.example.com/a","expect":"Your projects","screenshotPath":"~/.auspex/runs/s/screenshot.png","excerpt":"SECRET-LOGGED-IN-PAGE-TEXT account 12345678","verify":{"ok":true,"claimOk":false,"errors":[],"claimErrors":[],"anonymousClaimSkipped":true,"claimOkProfile":false,"runDir":"x"},"matched":false,"diff":{"previousReason":"matched","previousExpect":"Your projects","urlChanged":false,"excerptChanged":true,"sameUrl":true}} as never), true)),
  "classifySweepReceipt({\"name\":\"Projects\",\"url\":\"https://app.example.com/projects\",\"expect\":\"Your projects\"}, ...) #10": at(1790991898621, () => classifySweepReceipt(({"name":"Projects","url":"https://app.example.com/projects","expect":"Your projects"} as never), ({"schemaVersion":1,"ok":false,"reason":"mismatch","url":"https://app.example.com/a","expect":"Your projects","screenshotPath":"~/.auspex/runs/s/screenshot.png","excerpt":"SECRET-LOGGED-IN-PAGE-TEXT account 12345678","verify":{"ok":true,"claimOk":false,"errors":[],"claimErrors":[],"anonymousClaimSkipped":true,"claimOkProfile":false,"runDir":"x"},"matched":false,"diff":{"previousReason":"matched","previousExpect":"Checkpoint","urlChanged":false,"excerptChanged":true,"sameUrl":true}} as never), true)),
  "classifySweepReceipt({\"name\":\"first-file\",\"url\":\"https://app.example/f/1\",\"expect\":\"Page 1\"}, {\"schemaVersio...)": at(1790991898621, () => classifySweepReceipt(({"name":"first-file","url":"https://app.example/f/1","expect":"Page 1"} as never), ({"schemaVersion":1,"ok":false,"reason":"mismatch","url":"https://app.example.com/a","expect":"Your projects","screenshotPath":"~/.auspex/runs/s/screenshot.png","excerpt":"SECRET-LOGGED-IN-PAGE-TEXT account 12345678","verify":{"ok":true,"claimOk":false,"claimOkProfile":true},"matched":false} as never), true)),
  "classifySweepReceipt({\"name\":\"first-file\",\"url\":\"https://app.example/f/1\",\"expect\":\"Page 1\"}, {\"schemaVersio...) #2": at(1790991898621, () => classifySweepReceipt(({"name":"first-file","url":"https://app.example/f/1","expect":"Page 1"} as never), ({"schemaVersion":1,"ok":false,"reason":"mismatch","url":"https://app.example.com/a","expect":"Your projects","screenshotPath":"~/.auspex/runs/s/screenshot.png","excerpt":"SECRET-LOGGED-IN-PAGE-TEXT account 12345678","verify":{"ok":true,"claimOk":false,"claimOkProfile":false},"matched":false} as never), true)),
}
